### ISSUE TITLE
Xeva : XEnograft Visualization & Analysis

### ISSUE THREAD

**Issue by gangeshberiuhn** [Bioconductor/Contributions#1022]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bhklab/Xeva

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by spocks** [comment]
@lshep we have the same issue again! For 1st build we had only one warning *WARNING: Update R version dependency from 3.5 to 3.6* . I fixed this but now it says `build results were: "ABNORMAL" ` . 
Also there are 2 commits.

**Comment by gangeshberiuhn** [comment]
@Ishep It seems the webhook has been triggered once but there are 2 commits.

**Comment by lshep** [comment]
I still don't know why this is occurring and I am very sorry for the inconvenience this is causing.  I'll take over review of this package and can manually kick off builds so you can get an accurate report.

**Comment by spocks** [comment]
Hi @lshep : thank you for helping us out with package building. Please let us know if any more changes required before acceptance. The associated manuscript of the package in under revision and it requires bioconductor acceptance of the package. We will be very grateful if package can be accepted on bioconductor in coming weeks. Thanks again for your help!

**Comment by lshep** [comment]
Again I apologzie for this inconvenience and we apologize for being at a loss
for what is going on with the webhooks and build reports. 

Since there is still the issue with multiple builds occurring on a valid version
bump I would actually advise removing the webhook and requesting a manually
build to avoid the noise.  Just tag me and I'll try to kick one off quickly - If
you don't mind the noise you can keep the webhook active and I'll try to hop on
to kick off a build when I see it going crazy. 


**General**

- [ ] from the build report please fix the coding practices NOTES of using
  vapply instead of sapply and  seq_len() or seq_along() instead of 1:...
- [ ] We strongly encourage the use of unit tests to test correctness and
  accuracy of code 
- [ ] Why include the dontrun in the getExperiment? The exampels run
  instaneously
- [ ] Similarly why the dontrun in setResponse it seems to run fairly
  efficiently.  

**NEWS**
- [ ] Please remove the ============ at the bottom of the file. 


**NAMESPACE**
- [ ] There are a lot of exports please ensure that all of these should be
exposed to the user and that some of these should not be internal and only
called within other functions


**DESCRIPTION**
- [ ] Please remove `LazyData: true`  in our experience this rarely proves
useful and can often slow down installation of the package. 


**README**
- [ ] please also include Bioconductor install instructions 



**Vignette**
- [ ] I suggest changing the name of the vignette to the name of the
package. While this is entirely optional its is much more intuitive for a user to do `vignette("Xeva")` than try to hunt down the name of the vignette to do
`vignette("getting-started")` 
- [ ] Its fine that you start with an object to use for the example in the
vignette but considering the object is a specialized class you have created at
least reference the functions that the user can look at to create their own. 
 

**MAN**
- [ ] braca.Rd please include source information and more detail for this
dataset. 
- [ ] ALL man documents could use more detail. When looking at the documentation
when investigating the dontruns,  I can't figure out what most of the arugments
are in setResponse and getExperiment especially ones where you just indicate
default used. There should be explaintation of what these arguments are and how
they are used; if they are not used then they should be removed. This applies to all man
files/functions 
- [ ]  Please include an example for your class constructor - I currently have
no idea how to create an object of the class to be able to use in the vignette
pipeline since you provided the object already in your class format.  



**R code**
`General`
- [ ] We recommend the use of BiocParallel over parallel. Please explain if not
going to update
- [ ] ExpressionSets are outdated and have been replaced with
SummarizedExperiments.  Please update all instances unless you can provide very
good reasoning for not. 
- [ ] Remove commented out code. This should be added only when live


`XevaSet_Class.R`
- [ ] I have no idea how to create an object of your class 

`access_expressionData_functions.R`
- [ ] expressionsets are outdated. update to use a summarizedExperiment 
- [ ] we don't encourage half implemented code - remove .batch2DataFram and
batch_SummarizedMolProfiles and include only when code is live. (you should be
able to git track this) 

`access_slot_drug.R`
- [ ] Should there be any sort of validation for the replacement/setting of
drugInfo slot?  Does the data.frame need a particular format? 

`access_slot_expDesign.R`
- [ ] remove commented out code until live
- [ ] What about the case that both are not null?
- [ ] What happens in getBatchFormatted, when in the else? can all values still
be the default NULL or should something be defined? 

`access_slot_experiment.R`
- [ ] (optional) seems like the print method for the object class should be with
the class definition in XevaSet_Class.R.


`checkModel.R`
- [ ] Again optional but perhaps this is better placed with the XevaSet_Class.R
code. 

`creat_Experiment_slot.R`
- [ ] modelClassS4Vars()  where did these hard coded values come from?

`create_drug_slot.R`
- [ ] could this function be combined with a different file to reduce the number
of different files?  What is the point of this function? 

`create_modToBiobaseMap_slot.R/create_sensitivity_slot.R`
- [ ] Again completely optional but if these are validity methods (which it seems
like) then it is probably best to include in the file that has the class
definiation. 

Going to stop here but apply those general concepts above throughout.  Please ping when you are ready for a review and include a summary of the changes or comment on any questions placed above.  I can kick off a manual build when you are ready for review again to ensure the most accurate build report. 

Cheers and I look forward to working with you to getting the package accepted to Bioconductor.

**Comment by spocks** [comment]
Hi @lshep, thanks for your detailed comments. We have address all the comments and have made substantial changes in the code. The only thing that we can’t change at this moment is switch to SummarizedExperiments. As I have explained later also this is due to dependency on PharmacoGx package. We are working on the new release of PharmacoGx package where we plan to switch to SummarizedExperiments for both the packages. 
Please find our response to the issues below. We are looking forward to be accepted to Bioconductor.  

**General**
- [x] from the build report please fix the coding practices NOTES of using
vapply instead of sapply and seq_len() or seq_along() instead of 1:...
> We have replaced all sapply and 1:...

- [x] We strongly encourage the use of unit tests to test correctness and
accuracy of code
> We have performed unit tests for some important functions. In future we plan to update it for all necessary functions and will release it on github. 

- [x] Why include the dontrun in the getExperiment? The exampels run
instaneously
> We have fixed this issue.

- [x] Similarly why the dontrun in setResponse it seems to run fairly
efficiently.
> We have removed the dontrun from the function. 

**NEWS**

- [x] Please remove the ============ at the bottom of the file.
> We have fixed this issue.

**NAMESPACE**

- [x] There are a lot of exports please ensure that all of these should be
exposed to the user and that some of these should not be internal and only
called within other functions
> We have made sure that only the required functions are exported. We have also removed several functions from the export. 


**DESCRIPTION**

- [x] Please remove `LazyData: true` in our experience this rarely proves
useful and can often slow down installation of the package.
> We have fixed this issue.


**README**

- [x] please also include Bioconductor install instructions
> We have fixed this issue.


**Vignette**

- [x] I suggest changing the name of the vignette to the name of the
package. While this is entirely optional its is much more intuitive for a user to do `vignette("Xeva")` than try to hunt down the name of the vignette to do
`vignette("getting-started")`
> We have fixed this issue.


- [x] Its fine that you start with an object to use for the example in the
vignette but considering the object is a specialized class you have created at
least reference the functions that the user can look at to create their own.
> In the vignette, we have included a section to create object with an example and required data is also included.

**MAN**

- [x] braca.Rd please include source information and more detail for this
dataset.
> We have fixed this issue.


- [x] ALL man documents could use more detail. When looking at the documentation
when investigating the dontruns, I can't figure out what most of the arugments
are in setResponse and getExperiment especially ones where you just indicate
default used. There should be explaintation of what these arguments are and how
they are used; if they are not used then they should be removed. This applies to all man
files/functions
> Fixed. We have rechecked all the man documents to make sure all arguments are described.

- [x] Please include an example for your class constructor - I currently have
no idea how to create an object of the class to be able to use in the vignette
pipeline since you provided the object already in your class format.
> We have included a detailed example in the vignette.

**R code**
`General`

- [x] We recommend the use of BiocParallel over parallel. Please explain if not
going to update

- [x] ExpressionSets are outdated and have been replaced with
SummarizedExperiments. Please update all instances unless you can provide very
good reasoning for not.
> For both of these issues, at the moment it is not possible to switch. This is because of the dependency on another Bioconductor package from our group, PharmacoGx. We are working on the new version of PharmacoGx, where we plan to implement these changes in both Xeva and PharmacoGx.

- [x] Remove commented out code. This should be added only when live
> We have fixed this issue.

`XevaSet_Class.R`

- [x] I have no idea how to create an object of your class
> We have included an example in the function documentation. Furthermore a detailed example is also included in the Vignette under the section “Creating new Xeva object”.

`access_expressionData_functions.R`

- [x] expressionsets are outdated. update to use a summarizedExperiment
> This is because of the dependency on another Bioconductor package from our group, PharmacoGx. We are working on the new version of PharmacoGx, where we plan to implement these changes in both Xeva and PharmacoGx.

- [x] we don't encourage half implemented code - remove .batch2DataFram and
batch_SummarizedMolProfiles and include only when code is live. (you should be
able to git track this)
> We have reviewed the code and made sure no part of the code is half implemented.

`access_slot_drug.R`

- [x] Should there be any sort of validation for the replacement/setting of
drugInfo slot? Does the data.frame need a particular format?
> We have fixed this issue.


`access_slot_expDesign.R`

- [x] remove commented out code until live
> We have fixed this issue.


- [x] What about the case that both are not null?
> In such case batch will take precedent. Have included it in the details.

- [x] What happens in getBatchFormatted, when in the else? can all values still
be the default NULL or should something be defined?
> Fixed in code. Now in such case it returns error.

`access_slot_experiment.R`

- [x] (optional) seems like the print method for the object class should be with
the class definition in XevaSet_Class.R.
> We have fixed this issue.

`checkModel.R`

- [x] Again optional but perhaps this is better placed with the XevaSet_Class.R
code.
> The position of the code has been changed.

`creat_Experiment_slot.R`

- [x] modelClassS4Vars() where did these hard coded values come from?
> They are from Meehan, et al. Cancer research 77.21 (2017). Have added a note in the function also

`create_drug_slot.R`

- [x] could this function be combined with a different file to reduce the number
of different files? What is the point of this function?
> The position of the code has been changed.

`create_modToBiobaseMap_slot.R/create_sensitivity_slot.R`

- [x] Again completely optional but if these are validity methods (which it seems
like) then it is probably best to include in the file that has the class
definiation.
> The position of the code has been changed.

**Comment by lshep** [comment]
I just manually kicked off a build so you should get an accurate build report shortly

**Comment by spocks** [comment]
Hi @lshep Please push a manual built for the latest version. I have fixed a minor error from the last manual built. Thanks,

**Comment by gangeshberiuhn** [comment]
Ishep, could you please run a manual build? We have pushed all the changes and we want to see the results now. Thanks!

**Comment by spocks** [comment]
hi @lshep I think in the current built, warnings have nothing to do with the package
```Warning in readLines(file, skipNul = TRUE) :
  InternetOpenUrl failed: 'The operation timed out'
Error in readLines(file, skipNul = TRUE) : cannot open the connection
Calls: <Anonymous> ... checkDeprecatedPackages -> getAllDeprecatedPkgs -> read.dcf -> readLines
Execution halted```

**Comment by lshep** [comment]
Yes this ERROR is on our end and can be ignored for now -  Are you ready for a re-review?

**Comment by spocks** [comment]
yes

**Comment by lshep** [comment]
Clarification:  You say you can't switch to SummarizedExperiments because of the dependency on the PharmacoGx package however this dependency is not listed in the Description or the namespace?   In fact, it is not referenced at all in the documentation or the vignette.  How then is this package dependent on PharamcoGx? If this can be used in conjunction with the PharamcoGx package in a pipeline/workflow sort of way then this should be emphasized in the vignette and perhaps data from that package should be used instead of providing additional?  I see now that there are a few R files that say `copy from PharmacoGx`,  copying from another package even your own is not allowed and never encouraged.  If these functions are included in PharmacoGx then you should list PharmacoGx in the NAMESPACE and DESCRIPTION and import the necessary function to use in your package.  Please remove this code and import the necessary functions.

**Comment by spocks** [comment]
Hi @lshep I have removed the code copied from `PharmacoGx` and using the function directly from `PharmacoGx` package. I have updated the DESCRIPTION also. Hope this clarifies the last comment.

**Comment by gangeshberiuhn** [comment]
@lshep Could you please compile the package manually now? We have made the necessary changes to it.

**Comment by spocks** [comment]
Hi @lshep I have fixed an error in code that was in the build report. Could you please rerun it manually again? Thanks a lot,

**Comment by lshep** [comment]
So to avoid the massive amounts of postings that we are getting and subsequently emails -  You might want to just disable the webhook all together and just ping me when you need a rebuild.

**Comment by gangeshberiuhn** [comment]
@Ishep Could you please review the Xeva package, it's kinda urgent we have an urgent deadline. We have pushed the updated package and removed the webhook.

**Comment by lshep** [comment]
I kicked off a manual build to get the new accurate report.  I will review and get back to you within the next few days

**Comment by spocks** [comment]
Thanks @lshep for reviewing our package. I see in the current build report there is `ERROR: dependency PharmacoGx is not available for package Xeva` . Is it a build systems issue or error in our code? Let me know if I need to fix this, I will do it immediately. As @gangeshberiuhn mentioned we have a paper revision deadline so we thank you for making this priority. Looking forward to your review.

**Comment by lshep** [comment]
This should be an issue on our end. We updated the builders yesterday to reflect the current version of R-devel and we clean the packages.  I would hope after todays builds finish it would be able to find the package successfully.

**Comment by lshep** [comment]
I probably should email off list but since its somewhat related  @gangeshberiuhn  @spocks I'm having trouble loading PharmacoGx locally as well... 
```
```

**Comment by spocks** [comment]
@p-smirnov is the master of PharmacoGx. He can chime in here.

**Comment by lshep** [comment]
Other than that which really is an issue with PharmacoGx and not your package, I think it looks in good shape.  Please note for the Bioconductor installation instructions you'll want to update to "3.9" as your package will be released under that Bioconductor release not the current "3.8" release.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/gangeshberiuhn.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Xeva")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Xeva

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by gangeshberiuhn** [comment]
@mtmorgan I see that I already have a public ssh key and I assume this key has now been associated with the Repo but I want to get write access to the repo for b.haibe-kains.
