### ISSUE TITLE
dittoSeq

### ISSUE THREAD

**Issue by dtm2451** [Bioconductor/Contributions#1302]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dtm2451/dittoSeq

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by dtm2451** [comment]
It looks like the issues in the build report are coming from:
1. I need to update the R requirement from 3.6 to 4.0.  (-> warning in all builds that make it that far). I will do that.
2. Windows BUILD error: Seurat installation fails on the Windows build.  I see this for another package in Bioc already (http://bioconductor.org/checkResults/3.11/bioc-LATEST/Spaniel/tokay2-install.html), so I'm not sure I should do anything versus wait for this to hopefully be cleared up by the Seurat crew?
2. Mac CHECK errors: All issues are coming from instances when plotly hovering is attempted.  I've noticed plotly often does not always work out-of-the-box, but I'm not entirely sure why.  I'll look into this.

**Comment by LiNk-NY** [comment]
Hi Daniel, @dtm2451 
Thanks for taking a look. 
Please bump the version of the package for another build perhaps some of these have been resolved. 
Best, -M

**Comment by dtm2451** [comment]
1 is cleared, 2&3 are unchanged.  But 2 is likely to be cleared up in the future (and still shows up for other packages).  And 3 is a non-essential feature of the package.

**Comment by LiNk-NY** [comment]
Hi Daniel, @dtm2451 
Any updates on 3? It seems like the issue stems from loading the Cairo shared object file.

**Comment by dtm2451** [comment]
Unfortunately, I'm not really sure.  I can't seem to recreate this issue (running Mac R-3.6).

Within my code, the call is pretty simple: `plotly::ggplotly(p, tooltip = "text")`.  (This takes in a ggplot object and turns it into a ploty object using the "text" aes for building the hover display.)

The errors are a bit different, but based on https://stackoverflow.com/questions/38952427/include-cairo-r-on-a-mac, I wonder if the issue might be a bug with graphics connections in the Mac R-4.0 on the build machines?  Is there a way to tell if other packages in Bioconductor Import: or Suggest: plotly so we could check if it works elsewhere?

**Comment by dtm2451** [comment]
Update:
3. I have installed R-4.0 on my own machine (+Cairo) and dittoSeq installs and works just fine.  So I'm still inclined to think 2 & 3 are both issues on the build system end.

2. @lshep reported that the RccpParallel issue on tokay2 should be fixed and that should help with the Seurat install, though I think there may still be another issue, this time with 'uwot': http://bioconductor.org/checkResults/3.11/bioc-LATEST/Spaniel/tokay2-install.html
```
Error: package or namespace load failed for 'Seurat' in library.dynam(lib, package, package.lib):
 DLL 'uwot' not found: maybe not installed for this architecture?
```

**Comment by dtm2451** [comment]
Seurat issue is gone.
Mac Cairo-related issue remains.  Did you end up having a chance to look into that @lshep?

```
Error: .onLoad failed in loadNamespace() for 'Cairo', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so, 6): Symbol not found: _FcConfigGetCurrent
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so
  Expected in: flat namespace
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so
Execution halted
```

**Comment by lshep** [comment]
Please ignore this ERROR.  This is because the Cairo MAC binary is not available for R 4.0 yet.  We don't know when it will be available from CRAN.  Please proceed with the review ignoring this platform; it should clear up on its own whenever the binary becomes available.

**Comment by LiNk-NY** [comment]
Hi Daniel, @dtm2451 
Thank you for your patience in the review process. Reviews during the holiday break usually take longer. 
Please find your package review below. 

If you have any questions, please respond in the comments below. 

Best regards,
Marcel

---

# dittoSeq #1302

## DESCRIPTION

* Please format the description field to fit within the 80 character width.
* Looks good.

## NAMESPACE

* Are several `import*` functions necessary?

## vignettes

* Please update the formatting to fit the 80 character width. It is harder to
review the source document when the text is running off the page.
* The 'Bulk RNAseq data' section has some awkward code that uses `@`. Please use
extractor functions or include those data as separate objects
* Shouldn't `data.out` be part of the return value of the function rather than
an argument? The `show` method would perform the plotting

## R

* The class name is quite general and we would like 'RNAseq' to refer solely to
the method. Please change the name of your data class.
* I don't see why your data class cannot extend `SummarizedExperiment`.
* Please use endomorphic operations to resolve issues with `addPrcomp` and
related functions. A more straightforward approach would be to use `object` as
the first argument and require it to not be missing. Your return value would
be your data class with additional data.
* Avoid the use of `eval(parse(...))` and `typeof(x) == 'character'`
* For metadata, you can make use of the `metadata<-` generic and create a method
for your class.
* It appears that you are use S3 methods on an S4 class with `addMeta<-.RNAseq`.
Please see point above.
* Avoid using character input and instead use only the object.
* Create a wrapper for `message()` based on the `verbose` argument instead
of re-running `importDemux2Seurat` with `suppressMessages`.
* Check for package availability before using Seurat functions with
`requireNamespace` and creating conditional code that will error when the
package isn't available. See our guidelines for more information.
* For `ditto*` functions with a `data.out` argument, it would be good to
either break the function into two steps where you can use the data as input
to the plotting method or return the data with the plotting object somehow.
This is to avoid returning different objects based on input arguments.
* `RNAseq_mock` data can be the output of `importDESeq2` or `prcomp`. You can
then use this data to provide the `addDimReduction` example in the
documentation.
* Test class membership with `is(x, "classname")` avoid using `==` in
`getReductions`.
* Create accessor and setter functions for your class. There should be zero to
minimal use of the `@` function.
* `import*` functions can be reduced to one single function for your class with
conditional checks for suggested packages as described above.

## additional folders

* Please remove / move the extra folders in the package. Consider merging the
README.md files into one. Image assets can be placed in the vignettes or other
folder or in a separate GitHub repository for linking (as it seems like they are
only used for README files).

**Comment by LiNk-NY** [comment]
Hi Daniel, @dtm2451 
Any updates on the status of the package? 
Do you wish to proceed? Otherwise, I'd be forced to close the issue.
Thanks, 
Marcel

**Comment by dtm2451** [comment]
Hi Marcel, @LiNk-NY 
I do wish to proceed.  Sorry for not giving any updates.
It's a long list, but thanks for your review!
I'd had to focus on some other projects for the last few weeks, but I'm going to get started on making updates soon!
-Dan

**Comment by dtm2451** [comment]
Hello,
I've begun working on  these suggestions, but I do have a few questions:

1. For "Create a wrapper for message() based on the verbose argument instead of re-running importDemux2Seurat with suppressMessages," it's very likely that I am missing something, but my implementation does not actually run the function twice, so I'm not sure of the actual issue here.  Could you perhaps point me toward a message() wrapper usage example?

2. For "Shouldn't data.out be part of the return value of the function rather than an argument? The show method would perform the plotting": I currently return a pure ggplot object for all plotting functions except for dittoHeatmap. To my knowledge, best practice is to output pure ggplots, and I like this as it allows users to easily add extra ggplot modifications (Ex: `dittoDimPlot(...) + theme(...)`). The underlying data will rarely be needed by dittoSeq users, thus why it is normally not output, and (except in the case of dittoHeatmap) `data.out = TRUE` functionality was simply added for when this information might be needed for publication submission.  I would prefer to continue returning pure ggplot objects, but am certainly open to advice.

**Comment by dtm2451** [comment]
(only minor formatting changes have been made so far, version bump was more to the check if the package build issues are resolved.)

**Comment by dtm2451** [comment]
There's a different error output, but it's still confined to plotly data.hover usage.

**Comment by LiNk-NY** [comment]
> Hello,
> I've begun working on these suggestions, but I do have a few questions:
> 
> 1. For "Create a wrapper for message() based on the verbose argument instead of re-running importDemux2Seurat with suppressMessages," it's very likely that I am missing something, but my implementation does not actually run the function twice, so I'm not sure of the actual issue here.  Could you perhaps point me toward a message() wrapper usage example?

I'm not sure why the function ends early and loops back around (with `suppressMessages`) depending on `verbose`. I would create a wrapper `.msg` function that has inputs `txt` and `verbose`.
Then use that to output your messages rather than running it with `suppressMessages`. 


> 2. For "Shouldn't data.out be part of the return value of the function rather than an argument? The show method would perform the plotting": I currently return a pure ggplot object for all plotting functions except for dittoHeatmap. To my knowledge, best practice is to output pure ggplots, and I like this as it allows users to easily add extra ggplot modifications (Ex: `dittoDimPlot(...) + theme(...)`). The underlying data will rarely be needed by dittoSeq users, thus why it is normally not output, and (except in the case of dittoHeatmap) `data.out = TRUE` functionality was simply added for when this information might be needed for publication submission.  I would prefer to continue returning pure ggplot objects, but am certainly open to advice.

I guess following the 'pure' ggplot output is a bit more complicated. The show method would give you the plot but when assigning the object, you get the data and associated attributes. It may be easier to use the `ggplot` to create the heatmap so that it works well with the rest of the gg-based visualizations. 
Using an argument such as `data.out` is satisfactory. You could even have a helper function that extracts the data but this might be too much if you're only using it for the `dittoHeatmap` output. 

Thanks,
Marcel

**Comment by dtm2451** [comment]
Hi Marcel, @LiNk-NY 

> 1. Use a message wrapper instead of current suppressMessages implementation

I understand what you are suggesting now and will implement a `.msg <- function(verbose, text)`

> 2. Whether the `data.out` input can be used to change the outputs from plot -> underlying data

I am going to keep my current `data.out` functionality (I read "Using an argument such as data.out is satisfactory." as saying that it is okay).  On the heatmap side, I would love to keep the plot outputs consistent, but it's not trivial to make a heatmap from scratch in ggplot and I haven't found an ideal ggplot-based alternative to pheatmap. pheatmap itself is pretty commonly used.  For example, see `scater::plotHeatmap` (https://github.com/davismcc/scater/blob/master/R/plotHeatmap.R).

Thanks!
Dan

**Comment by dtm2451** [comment]
Question: Instead of conditional code that allows a function to continue, I have currently added `stop()`-code.  But that is not what is suggested https://bioconductor.org/developers/package-guidelines/#description and by you, is it?

> - Check for package availability before using Seurat functions with
requireNamespace and creating conditional code that will error when the
package isn't available. See our guidelines for more information.

My reasoning for dittoSeq:
- I don't want to force people to install (/troubleshoot the installation of) these packages in order to get dittoSeq.  Many Bioconductor users never use, and do not want to use, Seurat. The ability to add hovering using ggplotly conversion is a useful, but very non-essential feature. And both packages can be a headache to install. Thus: -> `Suggests:`
- The lack of Seurat / plotly means my functions really CANNOT do what they are requested to do when a Seurat (Seurat) object is given or when `do.hover = TRUE` (plotly). Thus, my current error > warning opinion.

But should I implement the below instead?
1. change the `stop()`s to `warning()`s followed by either empty `return()` for Seurat or `return(non_converted_ggplot)` for plotly
2. Then I can make conditional `expect_s3_class` & `expect_warning` unit tests.
- number 2 is not pretty, but should allow dittoSeq to pass the build test; The reason dittoSeq still has an error is that plotly does not seem to be installed on the tokay2 Windows build system.

**Comment by dtm2451** [comment]
It is *more* clear!  Although, I had honestly thought that my "But should I ..." section was what you and the guidelines truly suggest. Idk if I'm alone in that, but maybe the guidelines should be updated?

Anyway, I can keep my current method inside the functions than, and simply make some conditional unit testing.

I should have all your review suggestions implemented by the end of the week!

**Comment by LiNk-NY** [comment]
Hi Daniel, @dtm2451 
I see how you can interpret the guidelines this way. I can clarify the document a bit. 
Thanks for your feedback. 
-Marcel

**Comment by dtm2451** [comment]
No problem! thanks for your patience!  And the conditional check additions to my unit tests allowed successful building =)
-Dan

**Comment by dtm2451** [comment]
Hello @LiNk-NY,

I believe that I have now addressed all concerns in your review.  https://github.com/dtm2451/dittoSeq/issues/26 may provide an additional synopsis with individual points gathered together in terms of how I addressed them, as well as a few extra bits that I have either accomplished already, or will accomplish very soon.  But in direct response to your review...

> ## DESCRIPTION
> - Please format the description field to fit within the 80 character width.
> - Looks good.

I trimmed to 80 char, but I also did update the wording since your last review to get rid of the previous mention of my now scrapped RNAseq-class

> ## NAMESPACE
> - Are several import* functions necessary?

I take this to refer to my previous RNAseq-class import functions. Those are gone and replaced by a single importDittoBulk (imports as `SingleCellExperiment` (SCE)) with multiple S4 methods.

> ## vignettes
> - Please update the formatting to fit the 80 character width. It is harder to
review the source document when the text is running off the page.
> - The 'Bulk RNAseq data' section has some awkward code that uses @. Please use
extractor functions or include those data as separate objects

Trimmed to 80 char, updated the bulk RNAseq section to work with `SCE`/`SE` accessor functions.

> - Shouldn't data.out be part of the return value of the function rather than
an argument? The show method would perform the plotting

Discussed above, that the change between output types is proper here because it allows easiest addition of further ggplot manipulations like `dittoDimPlot(...) + theme(...)`, and there isn't an easy way to store/retrieve data from a ggplot object

> ## R
> - The class name is quite general and we would like 'RNAseq' to refer solely to
the method. Please change the name of your data class.
> - I don't see why your data class cannot extend SummarizedExperiment.

`RNAseq` scrapped for `SCE` which extends `SE`

> - Please use endomorphic operations to resolve issues with addPrcomp and
related functions. A more straightforward approach would be to use object as
the first argument and require it to not be missing. Your return value would
be your data class with additional data.

moved `object` to first input, and it is required to not be missing (DEFAULT removed altogether)

> - Avoid the use of eval(parse(...)) and typeof(x) == 'character'

The previous DEFAULT'ing strategy was removed altogether, along with as much eval(parse(...)) code as possible. (Accepting Seurat-v2 objects requires eval(parse(...)) because they didn't actually make all the constructor functions that they should have, and actually recommended access data like this.)

All `typeof(x) == 'type'` replaced with `is.'type'()`

> - For metadata, you can make use of the metadata<- generic and create a method
for your class.
> - It appears that you are use S3 methods on an S4 class with addMeta<-.RNAseq.
Please see point above.

The ability to add metadata was already constructed for `SCE`, so I nolonger create my own functions for this purpose.

> - Avoid using character input and instead use only the object.

Done. (alongside of removing the previous DEFAULT'ing strategy)

> - Create a wrapper for message() based on the verbose argument instead
of re-running importDemux2Seurat with suppressMessages.

Done. (`.msg_ifV()`)

> - Check for package availability before using Seurat functions with
requireNamespace and creating conditional code that will error when the
package isn't available. See our guidelines for more information.

Done, per our recent conversation above.

> - For ditto* functions with a data.out argument, it would be good to
either break the function into two steps where you can use the data as input
to the plotting method or return the data with the plotting object somehow.
This is to avoid returning different objects based on input arguments.

Discussed above, that the change between output types is proper here because it allows easiest addition of further ggplot manipulations like `dittoDimPlot(...) + theme(...)`

> - RNAseq_mock data can be the output of importDESeq2 or prcomp. You can
then use this data to provide the addDimReduction example in the
documentation.

The output of `example("importDittoBulk")` goes into `example("addDimReduction")` and the resulting `myRNA` is a full SCE that dittoSeq considers as bulk RNAseq data.  The RNAseq_mock in data/ has been removed.

> - Test class membership with is(x, "classname") avoid using == in
getReductions.

all `class()` and similar functions for checking class identity are replaces with `is(x, "classname")`

> - Create accessor and setter functions for your class. There should be zero to
minimal use of the @ function.

Not needed for the current `SCE` implementation as they are already made. However, perhaps my un-exported `.is_bulk()` function in utils.R is an export worthy accessor (with a different name of course)?

> - import* functions can be reduced to one single function for your class with
conditional checks for suggested packages as described above.

Done. None of the classes require conditional code. DGEList and SummarizedExperiment are imported in namespace.

> ## additional folders
> - Please remove / move the extra folders in the package. Consider merging the
README.md files into one. Image assets can be placed in the vignettes or other
folder or in a separate GitHub repository for linking (as it seems like they are
only used for README files).

README.md files were all merged.  Images were moved into the vignettes directory.  All other extra folders and files were removed.

**Comment by dtm2451** [comment]
(Just to summarize my recent update: I addressed a deprecation by ggplot and also added some extra functionality to a few of the Viz functions:
- Faceting, either automatically via a `split.by` input, or manually after requesting that necessary `extra.vars` be added to the `ggplot(data)` data.frames, was added to `dittoPlot`, `dittoDimPlot`, and `dittoScatterPlot`.)

**Comment by LiNk-NY** [comment]
Hi Daniel, @dtm2451 
Thanks for making those changes. The package is looking good!
Make sure that you change the package installation instructions so
that users obtain the package from Bioconductor release. 
I will approve your package shortly. 
Best,
Marcel

**Comment by dtm2451** [comment]
Hello @LiNk-NY,

Might there be an estimate for when I can expect dittoSeq to make it into the nightly build system? I cannot install via BiocManager::install("dittoSeq") yet.  Also, I've made further updates, but I can't know that they are error free on all OSs as I cannot trigger any builds.

I hope you are staying both safe and sane during these trying times!
Dan

**Comment by LiNk-NY** [comment]
Hi Dan, @dtm2451 
As soon as Martin @mtmorgan accepts your package into the manifest,
your package will show up in the nightly builds / build report. 
-Marcel

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dtm2451.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("dittoSeq")`. The package 'landing page' will be created at

https://bioconductor.org/packages/dittoSeq

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
