### ISSUE TITLE
New annotation R package (cellbaseR)

### ISSUE THREAD

**Issue by melsiddieg** [Bioconductor/Contributions#138]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/melsiddieg/cellbaseR

Confirm the following by editing each check box to '[x]'
- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x ] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by lawremi** [comment]
Going to need a lot of work. Glad @hpages is on it.

I can't tell what these queries return, because the structure of the data.frame is undocumented. But I'm guessing they should be standard Bioconductor range objects, not data.frame. The API is confusing, because e.g. `cbGeneClient()` sounds like it is giving me a client for querying, but instead it is actually perfoming the query. Presumably this could use the TxDb API, at least for some queries.

**Comment by melsiddieg** [comment]
Dear Sir

I am Mohammed OE Abdallah, a visiting researcher at the computational
biology lab at Cambridge university. I have developed an R package that
serves as an R client to CellBase web services https://github.com/opencb/
cellbase ,which enable quick and easy access to heterogeneous biological
information. CellBase takes full advantage of modern web technologies and
is powered by high availability and high-Performance NoSQL database which
results in almost real-time queries. Moreover, CellBase supports complex
queries by integrating and linking together different biological sources.
CellBase is currently used by many projects and institutions including;

- Genomics England (GEL) <http://www.genomicsengland.co.uk/>. Also known as
the 100K genomes project

- The EMBL-EBI European Variation Archive (EVA)
<http://www.ebi.ac.uk/eva/?Home>.

- The International Cancer Genome Consortium (ICGC) <https://dcc.icgc.org/>

and many others.

This R package makes use of the exhaustive RESTful Web service API that has
been implemented for CellBase. It enables researchers to query and obtain a
wealth of biological information from a single database saving a lot of
time. Another benefit is that researchers can easily make queries about
different biological topics and link all this information together as all
information is integrated.

Currently, Homo sapiens, Mus musculus, and a total of forty-eight species
are available and many others will be included soon. Results returned from
the CellBase queries are parsed into R data.frames and other common R data
structures so users can readily  get into downstream analysis.

The R package is named cellbaseR and is available at
https://github.com/melsiddieg/cellbaseR. I aim to make it available to
broader R community through Bioconductor, as I think it will significantly
simplify many annotations task in R, and is designed to be very
straightforward and easy to use.


Best regards

Mohammed OE Abdallah

**Comment by melsiddieg** [comment]
Dear Sir

This package is very similar in principle and functionality to BiomaRt
package (Querying REST web services), only much faster, integrated, and
versatile, that is also why it is very different from the regular R
annotation packages as it does not query a local database. We opted for a
data frame rather than genomic ranges as return value because not all the
query results are range date, the R client also fetch annotation for
transcription factors, clinical data, regulatory data, etc. a dataframe is
more consistent and can be easily converted into genomic ranges when
needed. I am fixing the issues right now, and hope to hear from you soon.

Best regards

Mohammed OE Abdallah

**Comment by lawremi** [comment]
The low-level query interface could output a data.frame, I guess, but it would be nice to have high-level accessors, like `genes()`, that return the appropriate data structure, rather than expecting the user to do it. 

Also, btw, if you used DataFrame you could call `expand()` instead of `unnest()` from tidyr and eliminate a dependency. I don't think data.table is needed there either.

It's not using BiocParallel correctly. For example, `Annovcf()` does not allow the user to pass down the _BiocParallelParam_ object to control the parallelization. You probably should not depend explicitly on the foreach package. 

The `readIds()` function reimplements VCF parsing. Please use `VariantAnnotation::readVcf()`. You could probably implement the existing VariantAnnotation API, e.g., `predictCoding()`, `locateVariants()`, using the web service, without introducing custom generics.

I'm not sure a web portal access package needs to implement any visualizations. If you returned appropriate data structures, the user could just pass them to GViz or whatever to make plots.

**Comment by melsiddieg** [comment]
We thought of implementing many convenience methods like snpByGene,
variantByRegion, and so on, but we found that we need a lot of  them to
cover the functionality of the web services, so we chose a middle-way
approach, however,  we might implement some if you suggest that. The
readIds function does not reimplement the vcf parser from the
VariantAnnotation
package as it merely reads and prepares the unparsed variants to be sent
through GET for remote annotation in the CellBase server, in that regards
it nicely complements the VariantAnnotation package by very fast (~ 1
minute for 10K variants) retrieval of a one-to-one corresponding data frame
of comprehensive variants annotations without the forcing the user download
any of the hefty annotations packages locally and doing the usual overlap
based annotations, the CellBase server also enables phased annotations as
well as structural variants annotations. You are right we could just
prepare the gene model data and drop the Gviz dependency.

Best wishes

**Comment by lawremi** [comment]
It's calling things like `strsplit()` so that's parsing in my book. I think you users would very much prefer convenient ways to get the common data types (like gene annotations) into standard data structures.

**Comment by melsiddieg** [comment]
Let me clarify the readIds point, we are just preparing the reads for the
REST call and none of it  is  parsed into R structures, only the response
of the GET call is parsed into R data frames, On the other hand,  the vcf
parser from the VariantAnnotation reads the vcf file into an R data frame
with all the added functionality, this does not serve our package in any
way.

**Comment by lawremi** [comment]
Please help me understand how calling `scanTabix()` and splitting on tab character is not reading the data into an R data structure. Sure, there's a ton of extra functionality in VariantAnnotation, but it's actually quite flexible, so you could disable most of the parsing (which happens in C instead of R) and probably get at least similar performance, with less work.

**Comment by melsiddieg** [comment]
Maybe I was not clear in my description, But my point is that none of the
read variants is returned to the user, it is all preparing the variants in
the specific way required by the CellBase server.

**Comment by melsiddieg** [comment]
Hi

We have now reached the phase where my package is passing all R CMD  checks
in all three platforms without errors, warnings, or notes, and all
Bioccheck without errors or warnings, however, I am getting this weird
error:

** checking loading without being on the library search path ... WARNING
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :

How can I fix this?

Best regards

**Comment by lshep** [comment]
Please ignore this warning for now. This is an issue on our end that we are in the process of correcting.

**Comment by hpages** [comment]
Hi Mohammed,

Thanks for submitting cellbaseR to Bioconductor. This sounds like a very promising package!

It has some serious usability issues though and some significant changes will be needed in order to address them. I'll start with the list below. I can't do more at the moment. Please address at your earliest convenience and I'll come back to this later.

Thanks,
H.

1) There should be an effort to reduce dependencies. Right now `library(cellbaseR)` takes more than 20 sec on my laptop because it requires the loading of 80 packages via a namespace (as reported by `sessionInfo()`)

2) All man pages use exactly the same text for \title and \description. For example, `?cbAnnotateVcf` gives me this:
```
  cbAnnotateVcf,CellBaseR-method    package:cellbaseR    R Documentation

  This method is a convience method to annotate a vcf files. This methods
  is ideal for annotating small to medium sized vcf files.

  Description:

     This method is a convience method to annotate a vcf files. This
     methods is ideal for annotating small to medium sized vcf files.
```
This text seems like an appropriate description but is not suitable for a title. Title should fit in 1 line, be as short as possible, and not be made of several sentences.

3) Please add examples to man pages for `cbAnnotateVcf` and `createGeneModel`.

4) There is no need to wrap the returned data.frame into a CellBaseResponse object. Just return the data.frame and get rid of the CellBaseResponse class. I'm sorry if you've been told otherwise.

5) The `"show"` method for CellBaseR objects should print an `\n` at the very end of its output to bring the prompt (`>`) back to the beginning of the following line:
```
    > show(cb)
    An object of class CellBaseR
    | it holds the configuration for querying the Cellbase databases
    | to change the default species from human use CellBaseR(species='')> 
```
  See the prompt at the end of the last line?

  The `"show"` method for CellBaseParam objects has the same problem.

6) Why isn't the `"show" `method for CellBaseR objects displaying the current species?
```
    > cb2 <- CellBaseR(species='dodo')
    > cb2
    An object of class CellBaseR
    | it holds the configuration for querying the Cellbase databases
    | to change the default species from human use CellBaseR(species='')> 
```
  Also the last line displayed suggests that the object is pointing at human which is not the case.

7) Is it expected that the species is not checked at construction time of the CellBaseR object?

8) The `CellBaseR()` constructor uses default values for some of its parameters (e.g. `host="http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/"`, `species="hsapiens"`). It is considered good practice to formalize this in the interface of the `CellBaseR()` function itself by having the default values for these arguments explicitly set to what they really are (instead of NULL as it is right now).

9) As Michael pointed out, the naming of the `cb*Client` methods is confusing because totally unconventional. The widely used convention for such functions is to use something like `getGenes` (instead of `cbGeneClient`), `getSnps` (instead of `cbSnpClient`), etc... You absolutely don't need (and shouldn't) use the `cb` prefix for all your generics/methods. It would make sense to do so if these were ordinary functions but since they are generics, you shouldn't. That's actually the whole point of using generic functions.

10) No need to display BiocStyle version at the top of the vignette. Maybe you meant to display the version of the cellbaseR package instead?

**Comment by melsiddieg** [comment]
Dear package reviewers

As you can see we have pushed many updates to our package in the last few
days to address the issues you raised. We made major changes to our package
to make more user-friendly and more inline with the Bioconductor
philosophy, These changes include:
1- Reducing the bloated dependency (improper import of Gviz), now the
library loads in two seconds, and have only one third of the dependencies
it used to have
2- Dropping the CellBaseResponse class, now the query results are returned
directly to the user
3- Renaming all CellBaseR methods to R/ Bioconductor Friendly names
4- Added many convenience functions , getClinicalByRegion,
getTranscriptByGen, etc
5- Added runnable examples to createGeneModel and AnnotateVcf
6- createGeneModel now only prepare the geneModel data and does not create
a GeneRegionTrack
7- fixed the documentation, more updates are still to come

Your feedback is much appreciated
Best regards

**Comment by melsiddieg** [comment]
We also corrected the implemntation of the BiocParallel, now the
BPPARAM=bpparam() is included in the function signature

**Comment by hpages** [comment]
Hi Mohammed,
All these changes sound like great improvements. Will look at them ASAP (in the next 24h) and will let you know. Thanks!
H.

**Comment by hpages** [comment]
Hi Mohammed,

I've been trying to access the cellbase webservice several times in the last 24 hours but I always get an HTTP error 404:
```
> library(cellbaseR)
> cb <- CellBaseR()
Error in open.connection(con, "rb") : HTTP error 404.
```
Is the service down? Any ETA for when the service will be available again?

Thanks,
H.

**Comment by melsiddieg** [comment]
Hi

Yes, unfortunately, we will try to resolve this as fast as possible.

**Comment by melsiddieg** [comment]
HI

We fixed that error, it turns out the CellBase version 4 server has been
promoted to  be the production server, Sorry for the inconvenience.

**Comment by melsiddieg** [comment]
Hi hpages

I have just pushed an  update to my package, and the I received the
following build report error

* Checking for bioc-devel mailing list subscription...
Error in curl::curl_fetch_memory(url, handle = handle) :
  Timeout was reached

I know this is not a real error as much as it is a short timeout issue
with the curl package    caused by slow DNS lookup of the test
machines

Best regards

**Comment by hpages** [comment]
Hi Mohammed,

Glad to hear that the CellBase service is up and running again. Thanks for drastically reducing the dependencies of cellbaseR (from 80 to only 32 packages). That makes a big difference when I load the package on my laptop: now `library(cellbaseR)` takes < 3 sec. instead of > 20 sec. :-)

About issue 2): you went to the extreme with man page titles that are now exactly the same as the name of the function. For example, the title for `AnnotateVcf` man page is AnnotateVcf. That is not exactly what I was trying to convey when I wrote that "Title should fit in 1 line, be as short as possible, and not be made of several sentences". A typical title for AnnotateVcf would be more like "Annotate a VCF file". The reason good titles are important is that they show up in the browser when people use the HTML browser interface to navigate the documentation of your package. See by yourself by starting the HTML interface with `help.start()`, then click on Packages, then on cellbaseR. That displays the list of all the man pages in your package in a 2-column table (aliases in the 1st column, man pages titles in the 2nd column). In your case the 2nd column is almost identical to the 1st column so is not very informative. Having titles that are a little bit more informative would help the user find what s/he's looking for.

About issue 3): `AnnotateVcf` still doesn't have examples.

About issue 7): I still think that the `CellBaseR()` constructor function should check the validity of the supplied species. Otherwise, when later on a get* function (e.g. `getGene()`) gives me back a 0-row data.frame, I have no way to tell if that's because I specified invalid genes or if I created a CellBaseR object pointing to a species that is not supported. And since I don't seem to have a way to know what species are supported, I'm a little bit in the dark as to what species I can supply when I call `CellBaseR()`.

Issue 8) was not addressed.

Other issues:

11) It looks like many of your get* functions ignore the `object` and `filters` arguments:
```
> getConservationByRegion
function (region, object = NULL, filters = NULL) 
{
    cb <- CellBaseR()
    res <- getRegion(object = cb, ids = region, resource = "conservation")
    res
}
<environment: namespace:cellbaseR>
> getGeneInfo
function (gene, object = NULL, filters = NULL) 
{
    cb <- CellBaseR()
    res <- getGene(object = cb, ids = gene, resource = "info")
    res
}
<environment: namespace:cellbaseR>
> getVariantAnnotation
function (variant, object = NULL, filters = NULL) 
{
    cb <- CellBaseR()
    res <- getVariant(object = cb, ids = variant, resource = "annotation")
    res
}
<environment: namespace:cellbaseR>
```
12) They would also need to present a more consistent interface:
```
> args(getGene)
function (object, ids, resource, filters = NULL, ...) 
NULL
```

13) Also why make some of them ordinary functions (e.g. `getGeneInfo`) and others generic functions with a method for CellBaseR objects (e.g. `getGene`).

14) You have a stale man page for `Annovcf` (that function doesn't seem to exist anymore).

Thanks,
H.

**Comment by melsiddieg** [comment]
Hi Hpages

issue 7 we are still working on this
issue 8  Here I catually took my guidance from this. stackoverflow
recommendation
http://stackoverflow.com/questions/28370249/correct-way-to-specifiy-optional-arguments-in-r-functions
| Sometimes you want to add a non-trivial default value, which might take
several lines of code to compute. Instead of inserting that code in the
function
| definition, you could use missing() to conditionally compute it if
needed. However, this makes it hard to know which arguments are required
and which are optional
| without carefully reading the documentation. Instead, I usually set the
default value to NULL and use is.null() to check if the argument was
supplied.

issue 11
 That was a work in progress when saw them, now they do not ignore the
object and filters

 issue 13
I Think there is some misunderstanding here:
All the core library of cellbaseR, ie, all the S4 methods that used to
start with cb has been renamed to getGene, getProtein, getRegion, etc.
We added many convenience functions that has the By in their name like
getSnpByGene, getClinicalByRegion, etc. All these functions are merely
wrapper functions around the S4 methods as you can see, with fewer
arguments and more direct approach. however like the biomaRt package we
don't plan to wrap everything and we still prefer people use the library
methods itself as this is more flexible, and maintianable and is a more
honest represntationo of the CellBase Api as it is nicely docuemnted here
 http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/
Better we provide very useful tips and up-to-date documentation for using
the Cellbase methods through the cbHelp function, for example you can see
all the avaiable resurces for a particular sucategory- gene, region,
variant, etc- through
| cbHelp(object=cb, subactegory="gene")

So you can get various gene data, for example, using the same method rather
than using six different wrapper functions.

documentation is still incomplete, but we will push more updates in that
regard

Best regards

**Comment by melsiddieg** [comment]
issue 3 I am still looking for small enough vcf file to use in the example,
can you recommend one ? I am looking for vcf file of less than 1K variants

**Comment by hpages** [comment]
Hi Mohammed,

Should I take a look at the latest version of cellbaseR (0.99.27)?

I forgot to say earlier that the HTML version of the vignette (cellbaseR.html) should be removed from the git tree. It will automatically be generated when we build the source tarball with `R CMD build`.

About issue 8: I agree with Hadley's recommendation to use a `NULL` default when the default value is non-trivial.  By non-trivial he means an expression that is not a single constant. However that doesn't apply to the `CellBaseR()` constructor function where all the default values would be single constants (except maybe for `api` and `tags` which are mysterious arguments, poorly documented, and seem to be ignored by the current implementation). Having these constants in the signature of the function and seeing them in the \usage section of the man page will add transparency/readability.

Thanks,
H.

**Comment by melsiddieg** [comment]
HI Hpages

Not yet, I am still rewriting many functions to accommodate your comments
and ironing some bugs, I expect to finish this in the coming few days

Best wishes

**Comment by hpages** [comment]
Hi Mohammed,

Should I take a look at the latest version of cellbaseR (0.99.28)?

Thanks,
H.

**Comment by melsiddieg** [comment]
Go ahead. I will push new updates very shortly

**Comment by hpages** [comment]
I'll wait for the updates then. Thanks!  H.

**Comment by hpages** [comment]
Hi Mohamed,

Did you push all your updates? Should I go ahead and take a look at the latest version of cellbaseR (0.99.29)? Please make sure all the issues I reported earlier are addressed. Thanks!

H.

**Comment by melsiddieg** [comment]
Hi @hpages 

Please have a look at the current version of CellbaseR, I have pushed fixes to issues 7 and 8 which are the only big issues remaining I guess. The build report mentions some issues with the Windows build that I think is related to Windows machine rather than the package.

**Comment by hpages** [comment]
Hi Mohammed,

I see some good progress. Thanks for your hard work! There are still some important usability issues though. See below. I hope that the package will be ready for the next BioC release in April. We don't have much time left!

Regards,
H.

**Issues reported previously**

- Issue #2 is still not properly addressed. You still have many man page titles that don't look like titles e.g. "This class defines the CellBaseR object", or "This Class defines a CellBaseParam object", etc... A title is not the typical subject+verb+complement sentence. This kind of sentences are for the \description section. Some of your \description sections actually repeat exactly the title which is somthing I already reported. For example the \title and \description in the CellBaseR-class man page are both "This class defines the CellBaseR object". Other man pages have this problem.

Also note that you have 2 man pages with title "CellbaseR": one is the man page for the cellbaseR package and the other one is the man page for the CellBaseR constructor function. This is potentially confusing. So I would suggest that you use titles like "The cellbaseR package" for the former and "The CellbaseR constructor" for the latter.

Please check the \title's and \description's of all your man pages and make sure they they follow these guidelines.

- Thanks for addressing issue #7 and for providing a mechanism to retrieve the list of supported species. This is a great addition.

- Thanks for adding argument default values to the interface of the `CellBaseR()` constructor (was issue #8).

- Issue #11: the supplied `filters` is still ignored in all `get*` ordinary functions e.g.
```
    > getConservationByRegion
    function (region, object = NULL, filters = NULL) 
    {
        if (!is.null(object)) {
            cb <- object
        } else {
            cb <- CellBaseR()
        }
        if (!is.null(filters)) {
            filters <- filters
        } else {
            filters <- NULL
        }
        res <- getRegion(object = cb, ids = region, resource = "conservation")
        res
    }
    <environment: namespace:cellbaseR>
```
  Note that this code:
```
        if (!is.null(filters)) {
            filters <- filters
        } else {
            filters <- NULL
        }
```
  does nothing so please remove it.
  It seems that `getConservationByRegion()` could just be implemented with something like:
```
    getConservationByRegion <- function(region, object=NULL, filters=NULL)
    {
        if (is.null(object))
            object <- CellBaseR()
        getRegion(object, ids=region, resource="conservation", filters=filters)
    }
```

- Issue #12: You provide 23 `get*` functions for querying the CellBaseR object passed to the `object` argument. 12 of them are generic functions and have the `object` argument in 1st position e.g.
```
    > args(getSnp)
    function (object, ids, resource, filters = NULL, ...) 
    NULL
```
  The other 11 get* functions are ordinary functions. They all have the `object` argument in 2nd position e.g.
```
    > args(getGeneInfo)
    function (gene, object = NULL, filters = NULL) 
    NULL
```
  Having the `object` argument sometimes in 1st position and mandatory, and sometimes in 2nd position and optional is going to alienate your users. Like here:
```
    > getCaddScores("19:45411941:T:C")
    ... OK ...
    > getChromosomeInfo(ids="22", resource="info")
    Error in (function (classes, fdef, mtable)  : 
      unable to find an inherited method for function ‘getChromosomeInfo’ for signature ‘"missing"’
```
  It seems that you decided to make the low-level functions generic and the higher level ones (i.e. the wrappers to the low-level ones) ordinary functions. This is kind of an arbitrary distinction that has no concrete advantages here but why not. Anyway that kind of distinction doesn't really matter from a user point of view and should be as transparent as possible. For the sake of user-friendliness, please use a more consistent interface for these functions. I suggest that you `object` in 1st position everywhere.
  
I realize that making `object` an optional argument is somewhat convenient but if this kind of convenience is desirable then why not replace the generics by ordinary functions and have all the `get*` functions do that? I would not encourage this but that would still be better than the current situation. Note that if you choose that route then the default for 'object' should preferably be set to `CellBaseR()` instead of `NULL` in the signature of all the functions. This would reflect what the default actually is (something that the man pages doesn't say, the user has to guess).

**Other issues**

15. All the man pages for the `get*` generic functions have the same \details section:
```
     Please, for details on possible values for the parameters and
     additional filters of this function refer to
     https://github.com/opencb/cellbase/wiki and the RESTful API
     documentation http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/
```
So where should go the user that wants to learn more about what value can be passed to the `resource` argument? To the wiki on github or to the RESTful API documentation? Both are big and hard to navigate (RESTful API documentation website is very cryptic). After spending a couple of minutes trying to find what the `resource` argument can be I gave up. This needs to be revisited/improved. Couldn't the `cbHelp()` function be used to get that information? I don't know, the man page for `cbHelp` is also very minimalist, Right now, this situation makes the cellbaseR package very hard to use.

16. Please don't put the ellipsis (`...`) in the signature of the `get*` generic functions. You don't need it and it hurts usability by silently absorbing mistyped arguments. For example, because of the ellipisis the following works:
```
    getTranscript(cb, ids="ENST00000373644", resource="info",
                  param=CellBaseParam(genome="GRCh38"))
```
when it should fail (the `param` argument doesn't exist). Even worse: it returns the "wrong" result i.e. the transcript for the default human assembly (GRCh37) which is not what the user was asking for.

17. Most users would expect CellBaseParam objects to be passed thru a `param` argument, not thru a `filters` argument. They would expect that the `filters` argument is an object named something like CellBaseFilters instead. So please either rename the 'filters' argument or rename the CellBaseParam class. Make sure to use plural or singular for both: the class name and the argument name. Using consistent names greatly helps in making your software more user-friendly.

18. In the same spirit, please use more consistent argument names *across* your functions. For example why would the user pass the regions to an argument named `ids` when calling `getRegion()` and to an argument named `region` when calling `getConservationByRegion()`?

Note that once you use the same argument name for the regions passed to `getRegion()` and `getConservationByRegion()` then the latter becomes a very thin wrapper around the former. Does it still add enough value to justify the wrapper?
  
19. I understand that not all genomic annotations are available for mmusculus but this would need to fail more graciously:
```
    > getCaddScores("19:45411941:T:C", CellBaseR(species="mmusculus"))
    Note that not all genomic annotations are avaiable for mmusculus 
    Error: lexical error: invalid char in json text.
                                           <!DOCTYPE html><html><head><tit
                         (right here) ------^
```

20. Please indent your code properly. For example do
```
    fl <- system.file("extdata", "hapmap_exome_chr22_500.vcf.gz",
                      package = "cellbaseR" )
```
  instead of
```
    fl <- system.file("extdata", "hapmap_exome_chr22_500.vcf.gz",
    package = "cellbaseR" )
```
  which is hard to read.

21. Many occurrences of "avaiable" (instead of "available") in the documentation. Also "aviable" found in "see ?getMeta examples to see the aviable species".

22. Incomplete sentence in "Note that not all genomic annotations are avaiable for":
```
> res <- getMeta(cb, resource="species")
Note that not all genomic annotations are avaiable for  
```

23. As mentioned earlier, the HTML version of the vignette (cellbaseR.html) needs to be removed from the git tree. It will automatically be generated when we build the source tarball with `R CMD build cellbaseR`.

**Comment by melsiddieg** [comment]
Thanks for the valuable feedback. I will start addressing these issues
immediately.

**Comment by melsiddieg** [comment]
Hi @hpages 
Thanks for the valuable feedback it has been very educational to me, and I think I learned a lot in the process.
I have addressed all the issues you raised in the updates I pushed through the weekend
Please have a look at the current version of cellbaseR
Hopefully, cellbaseR is now more consistent and less cluttered and has better documentation
issue 2  better documentation
issue 15 -- Yes this is the job of formerly cbHelp, which now has been renamed to getCellBaseResourceHelp. I also improved its documentation
issue 16 removed unnecessary ellipsis
issue 17 the filters argument has been renamed to param
issue 18 id is used for the sake of consistency
issue 19 - 23 all addressed

**Comment by melsiddieg** [comment]
Hi @hpages

I hope you had time to review all changes we made since your last comment.

**Comment by hpages** [comment]
Hi Mohammed,

Thanks for addressing all the issues. I'm marking the package as accepted. We will add it to our Subversion repo and build system in the next days. You'll receive an email with more information about this.
Congratulations and thanks for your patience and all your efforts during the review process!
H.
