### ISSUE TITLE
TMExplorer

### ISSUE THREAD

**Issue by LordSushiPhoenix** [Bioconductor/Contributions#1533]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/shooshtarilab/TMExplorer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Without looking at the code in any detail at all, it would seem essential to interoperate with the Bioconductor ecosystem by representing single-cell RNA-seq datasets as [SingleCellExperiment][1] objects, and hence having this package in your Depends: field (because you will return these for the user to consume.

[1]: https://bioconductor.org/packages/SingleCellExperiment

**Comment by LordSushiPhoenix** [comment]
Currently TMExplorer does not use SingleCellExperiment objects, but I'm working on adding support for them.

Is there a way to avoid the `\value` warning when using roxygen2 to generate documentation? Currently I'm using `@section Value: ...` which adds a value section to the manpages but not as `\value{}`

**Comment by lshep** [comment]
I believe this was answered on the bioc-devel mailing list.  `@return`

**Comment by LordSushiPhoenix** [comment]
Yup it was, I've updated the tags in the main branch.

**Comment by nturaga** [comment]
Please issue a new build report.

**Comment by nturaga** [comment]
# TMExplorer review

## Build

ok

## INSTALL

ok

## DESCRIPTION

- ok

## NAMESPACE

- ok

## vignette

- ok

## R

* Remove commented out code.

* Use `\donttest` instead of `\dontrun` in examples, but either way,
  you need to have some examples which run without either of them.
  
  ```
  * Checking man page documentation...
    * NOTE: Usage of dontrun{} / donttest{} found in man page examples.
      100% of man pages use one of these cases.
      Found in the following files:
        queryTME.Rd
  ```

* Remove `sysdata.rda` file from `R/` directory.

* man pages for the functions need to be more elaborate.

**Comment by LordSushiPhoenix** [comment]
I'm currently using `\donttest` and `\dontrun` because of how long the examples take to run since they download data. I can create an example dataset that will download quicker, but can't think of any way to improve the speed at which `res <- queryTME(has_truth = TRUE, has_signatures = TRUE)` runs since it returns multiple matching datasets. 

Where should I put `sysdata.rda` if not the `R/` directory? According to the package guidelines that's where internal data should go.

When you say that the man pages need to be more elaborate, should I elaborate on the function description or the argument descriptions?

**Comment by LordSushiPhoenix** [comment]
Apologies for the late reply, `sysdata.rda` is internal data that will always be operated on before it is exported to the user, the full contents of the file are never exported. 

I had not considered AnnotationHub, but reading through that vignette I believe it would work. It says that temporary access to an S3 bucket is granted, how long does this access last? I'm currently trying to set up a server to host the data (right now it is hosted on onedrive) but due to the COVID-19 pandemic I'm not sure when it will be ready.

**Comment by nturaga** [comment]
> Apologies for the late reply, `sysdata.rda` is internal data that will always be operated on before it is exported to the user, the full contents of the file are never exported.
> 
> I had not considered AnnotationHub, but reading through that vignette I believe it would work. It says that temporary access to an S3 bucket is granted, how long does this access last? I'm currently trying to set up a server to host the data (right now it is hosted on onedrive) but due to the COVID-19 pandemic I'm not sure when it will be ready.

I believe this is based on Lori Shepherd's (@lshep - who manages the Hubs) decision. I would suggest you start the process as soon as possible. 

The annotation hub method is a cleaner solution. If you want this package to be accepted in this devel cycle, you should try and get it done in a week or so.

**Comment by lshep** [comment]
You are welcome to host on your own server or use Bioconductor's S3 hosted services.  The temporary access to upload files would be active for a few weeks before deactivating.  If you would like to upload the data for hosting on the Bioconductor S3 server please send an email to hubs@bioconductor.org to request the credentials.  We would also need the metadata.csv file and DESCRIPTION files updated as described in [Creating An AnnotationHub Package](http://bioconductor.org/packages/release/bioc/vignettes/AnnotationHub/inst/doc/CreateAnAnnotationPackage.html).   Cheers

**Comment by LordSushiPhoenix** [comment]
Thanks, @nturaga and @lshep. After the upload period of a few weeks is deactivated, will the data still be hosted on the S3 server?

**Comment by lshep** [comment]
The temporary credentials are only to allow you to upload the data.  Currently there is no expiration and the data will be hosted indefinitely

**Comment by LordSushiPhoenix** [comment]
Hi @nturaga, after more consideration, I'm not sure AnnotationHub is the best solution for our data. The data is curated, with some of the raw content removed and in some cases additional information is added. 

Additionally, moving the data to AnnotationHub will not help with the memory usage that I am trying to avoid with `dontrun` and `donttest` in `queryTME.Rd`. With this in mind, I can add more examples that run without those tags, but would like to keep the examples that require one tag in place. Will this be acceptable?

**Comment by LordSushiPhoenix** [comment]
I am not sure what has caused that build error, it builds fine using R 4.0.2 and Bioconductor 3.12 on my machine. Is there an issue with the build system? (Build log follows)

```
R CMD build --keep-empty-dirs --no-resave-data TMExplorer
* checking for file ‘TMExplorer/DESCRIPTION’ ... OK
* preparing ‘TMExplorer’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘TMExplorer_0.99.5.tar.gz’
```

**Comment by lshep** [comment]
I'll try and kick off another manual build of the package to see if this clears on the build report.

**Comment by lshep** [comment]
I'll go on the builder to investigate and try to have more information soon.

**Comment by lshep** [comment]
There was a recent report on the Bioconductor community slack and reported issue that the recent release of knitr is incompatible with BiocStyle.   [report issue](https://github.com/Bioconductor/BiocStyle/issues/78)  I would suspect that this is also causing problems for your package as the Single Package Builder uses the latest versions of all released packages.  There is nothing you need to do regarding this ERROR at this time.  Let @nturaga know when you have addressed the other concerns for a re-review.   If @nturaga  didn't mention it - You might consider renaming your vignette to at least the name of your package.  tutorial is very very generic and depending what other packages a user has loaded, can result in the wrong vignette being displayed.

**Comment by LordSushiPhoenix** [comment]
Thanks, @lshep, good call on the vignette name, that isn't something I had thought of. I'll push a few more changes later today and then it should be ready for @nturaga to re-review.

**Comment by LordSushiPhoenix** [comment]
Hi, @nturaga I believe I have addressed all concerns now. 

All commented out code is removed, new examples that do not rely on `\donttest` or `\dontrun` were added, and the man pages are now more elaborate.

**Comment by nturaga** [comment]
You still have an ERROR on your build report. I cannot accept the package while it's failing the build report. Get it to pass the build report and I'll accept it.

**Comment by lshep** [comment]
I'm rerunning the package now.  @nturaga  this is an artifact of the BiocStyle/knitr issue as discussed above -- hopefully with the rerun it should be clear.  the build report should post shortly

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LordSushiPhoenix.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("TMExplorer")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TMExplorer

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
