### ISSUE TITLE
MAGAR - Methylation Aware Genotype Association in R

### ISSUE THREAD

**Issue by schmic05** [Bioconductor/Contributions#1787]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MPIIComputationalEpigenetics/MAGAR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by hpages** [comment]
Thanks @schmic05 for submitting MAGAR. Here is some feedback:

1. The package implements two S4 classes to handle methylation data: methQTLInput and methQTLResult. Is that necessary? Couldn't some of the existing data structures already implemented in one of the many Bioconductor packages that deal with methylation data be reused instead? Some of the most outstanding data structures seem to be RnBeadSet in RnBeads, MethylSet in minfi, MethyLumiSet in methylumi, BSdataSet in methylPipe, BSrel and BSraw in BiSeq, etc... See the [DNAMethylation view](https://bioconductor.org/packages/release/BiocViews.html#___DNAMethylation) for the full list of Bioconductor packages that deal with methylation data.
  FWIW [I asked](https://stat.ethz.ch/pipermail/bioc-devel/2020-December/017546.html) on the bioc-devel mailing list for any suggestion/advice about this and I'll let you know if I hear anything. You're of course more than welcome to watch the list and to participate to the discussion. 

2. The package also defines IO functions `saveMethQTL`/`loadMethQTL` and `saveMethQTLResult`/`loadMethQTLResult` to save/load methQTLInput and methQTLResult objects to/from disk. Why the inconsistent naming scheme?

3. `R CMD BiocCheck` produces 10 NOTEs which is a lot. Please address as much of them as possible.

4. It's not a good idea to make the path to an executable version of Rscript an option (`rscript.path`). This can only get you or your user into trouble e.g. this fails for me:
    ```
    > example(qtlOptions2JSON)

    qO2JSO> {
    qO2JSO+   qtlSetOption('cluster.cor.threshold'=0.5)
    qO2JSO+   qtlOptions2JSON("my_opts.json")
    qO2JSO+   qtlJSON2options("my_opts.json")
    qO2JSO+ }
    sh: 1: /usr/bin/Rscript: not found
    2020-12-10 11:53:32     1.2   ERROR Invalid value for rscript.path. Needs to be a path to an executable version of Rscript
    Error in logger.error("Invalid value for rscript.path. Needs to be a path to an executable version of Rscript") : 
      Invalid value for rscript.path. Needs to be a path to an executable version of Rscript
    ```
    More importantly even if this default path was valid there's no guarantee that it's pointing to the same R instance as the running instance. And if it's not, then bad things will happen. So making `rscript.path` a user-controlled setting makes little sense when the standard and reliable way to get this path is with something like `file.path(R.home("bin"), "Rscript")`.

5. More generally speaking, the number of global options (40!) that methQTL calculation relies on is a concern. Please try to reduce this number as much as possible.

6. Some of the functions defined, exported and documented in the package don't seem to be intended to be used directly by the user. For example `doGenoImport()`, `doGenoImportIDAT()`, `doGenoImportImputed()` are not used in the vignette and don't have examples. Note that there is no need to export and document internal utilities. In any case all man pages should have examples and you have a dozen or so man pages that don't.

7. The vignette says:

    > After installing the dependencies, MAGAR can be installed from GitHub, after installing the devtools package.

    However this is not how a Bioconductor package should be installed. Because of Bioconductor 6-month release cycles and because Bioconductor has a notion of release and devel, Bioconductor users should always use `BiocManager::install()` to install packages. This will spare them a lot of headaches with version mismatches. Please instruct your users to install the package with `BiocManager::install()` and do not encourage them to install from GitHub.

8. The proper/portable way to use `system.file()` is:
    ```
    system.file("extdata", "reduced_methQTL", package="MAGAR")
    ```
    rather than:
    ```
    system.file("extdata/reduced_methQTL",package="MAGAR")
    ```

9. I'm not sure there's any benefit in wrapping the man page examples in curly braces like here:
    ```
    {
    meth.qtl <- loadMethQTL(system.file("extdata/reduced_methQTL",package="MAGAR"))
    meth.data <- getMethData(meth.qtl)
    anno.meth <- getAnno(meth.qtl,"meth")
    cor.blocks <- computeCorrelationBlocks(meth.data,annotation=anno.meth)
    }
    ```

Thanks,
H.

**Comment by vjcitn** [comment]
I was unable to build the vignette on my system.  
```
stvjc@stvjc-XPS-13-9300:~/SUBMISSIONS$ Rdev CMD build MAGAR
1/9 packages newly attached/loaded, see sessionInfo() for details.
* checking for file ‘MAGAR/DESCRIPTION’ ... OK
* preparing ‘MAGAR’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘MAGAR.Rmd’ using rmarkdown
Quitting from lines 164-168 (MAGAR.Rmd) 
Error: processing vignette 'MAGAR.Rmd' failed with diagnostics:
invalid value for option assembly
--- failed re-building ‘MAGAR.Rmd’

SUMMARY: processing the following file failed:
  ‘MAGAR.Rmd’

Error: Vignette re-building failed.

```
> sessionInfo()
R Under development (unstable) (2020-12-08 r79595)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS (fossa-melisa X20)

Matrix products: default
BLAS:   /home/stvjc/R-dev-dist/lib/R/lib/libRblas.so
LAPACK: /home/stvjc/R-dev-dist/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
 [1] grid      parallel  stats4    stats     graphics  grDevices utils    
 [8] datasets  methods   base     

other attached packages:
 [1] MAGAR_0.99.0                           
 [2] crlmm_1.49.1                           
 [3] preprocessCore_1.53.1                  
 [4] oligoClasses_1.53.0                    
 [5] snpStats_1.41.1                        
 [6] survival_3.2-7                         
 [7] RnBeads_2.9.0                          
 [8] plyr_1.8.6                             
 [9] methylumi_2.37.0                       
[10] minfi_1.37.0                           
[11] bumphunter_1.33.0                      
[12] locfit_1.5-9.4                         
[13] iterators_1.0.13                       
[14] foreach_1.5.1                          
[15] Biostrings_2.59.0                      
[16] XVector_0.31.0                         
[17] SummarizedExperiment_1.21.0            
[18] FDb.InfiniumMethylation.hg19_2.2.0     
[19] org.Hs.eg.db_3.12.0                    
[20] TxDb.Hsapiens.UCSC.hg19.knownGene_3.2.2
[21] GenomicFeatures_1.43.2                 
[22] AnnotationDbi_1.53.0                   
[23] reshape2_1.4.4                         
[24] scales_1.1.1                           
[25] Biobase_2.51.0                         
[26] illuminaio_0.33.0                      
[27] limma_3.47.1                           
[28] gridExtra_2.3                          
[29] gplots_3.1.1                           
[30] ggplot2_3.3.2                          
[31] fields_11.6                            
[32] spam_2.5-1                             
[33] dotCall64_1.0-0                        
[34] ff_4.0.4                               
[35] bit_4.0.4                              
[36] cluster_2.1.0                          
[37] MASS_7.3-53                            
[38] GenomicRanges_1.43.0                   
[39] GenomeInfoDb_1.27.2                    
[40] HDF5Array_1.19.0                       
[41] rhdf5_2.35.0                           
[42] DelayedArray_0.17.4                    
[43] IRanges_2.25.4                         
[44] S4Vectors_0.29.6                       
[45] MatrixGenerics_1.3.0                   
[46] matrixStats_0.57.0                     
[47] BiocGenerics_0.37.0                    
[48] Matrix_1.2-18                          
[49] rmarkdown_2.5                          

loaded via a namespace (and not attached):
  [1] VGAM_1.1-4                RcppEigen_0.3.3.7.0      
  [3] BiocFileCache_1.15.1      igraph_1.2.6             
  [5] splines_4.1.0             BiocParallel_1.25.1      
  [7] digest_0.6.27             htmltools_0.5.0          
  [9] magrittr_2.0.1            memoise_1.1.0            
 [11] doParallel_1.0.16         bigassertr_0.1.3         
 [13] bigstatsr_1.3.1           readr_1.4.0              
 [15] annotate_1.69.0           askpass_1.1              
 [17] siggenes_1.65.0           prettyunits_1.1.1        
 [19] colorspace_2.0-0          blob_1.2.1               
 [21] rappdirs_0.3.1            xfun_0.19                
 [23] dplyr_1.0.2               jsonlite_1.7.2           
 [25] crayon_1.3.4              RCurl_1.98-1.2           
 [27] genefilter_1.73.0         impute_1.65.0            
 [29] GEOquery_2.59.0           flock_0.7                
 [31] glue_1.4.2                gtable_0.3.0             
 [33] zlibbioc_1.37.0           UpSetR_1.4.0             
 [35] Rhdf5lib_1.13.0           maps_3.3.0               
 [37] mvtnorm_1.1-1             bigparallelr_0.3.0       
 [39] DBI_1.1.0                 rngtools_1.5             
 [41] Rcpp_1.0.5                xtable_1.8-4             
 [43] progress_1.2.2            mclust_5.4.7             
 [45] httr_1.4.2                RColorBrewer_1.1-2       
 [47] ellipsis_0.3.1            pkgconfig_2.0.3          
 [49] reshape_0.8.8             XML_3.99-0.5             
 [51] dbplyr_2.0.0              tidyselect_1.1.0         
 [53] rlang_0.4.9               munsell_0.5.0            
 [55] tools_4.1.0               generics_0.1.0           
 [57] RSQLite_2.2.1             argparse_2.0.3           
 [59] evaluate_0.14             stringr_1.4.0            
 [61] knitr_1.30                bit64_4.0.5              
 [63] beanplot_1.2              caTools_1.18.0           
 [65] scrime_1.3.5              purrr_0.3.4              
 [67] nlme_3.1-150              doRNG_1.8.2              
 [69] sparseMatrixStats_1.3.2   nor1mix_1.3-0            
 [71] xml2_1.3.2                biomaRt_2.47.1           
 [73] startup_0.15.0            compiler_4.1.0           
 [75] filelock_1.0.2            curl_4.3                 
 [77] affyio_1.61.0             tibble_3.0.4             
 [79] stringi_1.5.3             lattice_0.20-41          
 [81] multtest_2.47.0           vctrs_0.3.5              
 [83] pillar_1.4.7              lifecycle_0.2.0          
 [85] rhdf5filters_1.3.3        BiocManager_1.30.10      
 [87] cowplot_1.1.0             data.table_1.13.4        
 [89] bitops_1.0-6              rtracklayer_1.51.0       
 [91] R6_2.5.0                  KernSmooth_2.23-18       
 [93] codetools_0.2-18          gtools_3.8.2             
 [95] assertthat_0.2.1          openssl_1.4.3            
 [97] withr_2.3.0               GenomicAlignments_1.27.1 
 [99] Rsamtools_2.7.0           GenomeInfoDbData_1.2.4   
[101] hms_0.5.3                 quadprog_1.5-8           
[103] tidyr_1.1.2               base64_2.0               
[105] DelayedMatrixStats_1.13.1 ellipse_0.4.2            
> 

```

**Comment by schmic05** [comment]
Hi @vjcitn,

Sorry, I forgot to synchronize the GitHub version of the package with the Bioconductor-GitHub version. This was something that I should already have fixed.

**Comment by vjcitn** [comment]
Thank you, the problem persists after a new pull of your repo.  I see a .Rproj file that should not be present.  Here are a few more comments.

You should not be using installation commands in a vignette.  All installation is
handled using the DESCRIPTION file and BIocManager
```
> 
> ## ----installation, echo=FALSE, eval=TRUE--------------------------------------
> if(!requireNamespace(" ..." ... [TRUNCATED] 
Loading required namespace: devtools

> if(!requireNamespace("RnBeads")){
+ 	source("https://rnbeads.org/data/install.R")
+ }
Loading required namespace: RnBeads
Setting options('download.file.method.GEOquery'='auto')
Setting options('GEOquery.inmemory.gpl'=FALSE)

> if(!requireNamespace("MAGAR")){
+   devtools::install_github("MPIIComputationalEpigenetics/MAGAR")
+ }  
Loading required namespace: MAGAR
No methods found in package ‘oligoClasses’ for request: ‘mean’ when loading ‘crlmm’

> suppressPackageStartupMessages(library(MAGAR))
51/0 packages newly attached/loaded, see sessionInfo() for details.
```
Here is the fatal error

```
> meth.qtl.res <- doMethQTL(imp.data,default.options=FALSE,p.val.cutoff=0.05)
Error in (function (...)  : invalid value for option assembly
In addition: Warning message:
no function found corresponding to methods exports from ‘RnBeads’ for: ‘samples’ 

Enter a frame number, or 0 to exit   

 1: source("MAGAR.R", echo = TRUE)
 2: withVisible(eval(ei, envir))
 3: eval(ei, envir)
 4: eval(ei, envir)
 5: MAGAR.R#97: doMethQTL(imp.data, default.options = FALSE, p.val.cutoff = 0.0
 6: imputeMeth(meth.qtl)
 7: imputeMeth(meth.qtl)
 8: rnb.xml2options(qtlGetOption("rnbeads.options"))
 9: do.call(rnb.options, option.values)
10: do.call(rnb.options, option.values)
11: (function (...) 
{
    optlist <- list(...)
    if (length(optlist) == 0) {
```

**Comment by vjcitn** [comment]
I closed it by accident
```
> sessionInfo()
R Under development (unstable) (2020-12-08 r79595)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS (fossa-melisa X20)

Matrix products: default
BLAS:   /home/stvjc/R-dev-dist/lib/R/lib/libRblas.so
LAPACK: /home/stvjc/R-dev-dist/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
 [1] grid      parallel  stats4    stats     graphics  grDevices utils    
 [8] datasets  methods   base     

other attached packages:
 [1] XML_3.99-0.5                           
 [2] MAGAR_0.99.5                           
 [3] crlmm_1.49.1                           
 [4] preprocessCore_1.53.1                  
 [5] oligoClasses_1.53.0                    
 [6] snpStats_1.41.1                        
 [7] survival_3.2-7                         
 [8] RnBeads_2.9.0                          
 [9] plyr_1.8.6                             
[10] methylumi_2.37.0                       
[11] minfi_1.37.0                           
[12] bumphunter_1.33.0                      
[13] locfit_1.5-9.4                         
```

**Comment by schmic05** [comment]
Thanks for your comments. I will change the vignette accordingly in my process of going through hpages' comments. 
The issue that you report is with a missing package (RnBeads,hg19), which I added to the Suggests field in a recent update. So the R CMD build should work. Anyway, I'll address the comments and let the two of you know after fixing the issues.

**Comment by schmic05** [comment]
Hi @hpages 

Thanks a lot for having a look at the package and for your detailed information. I addressed some of your comments and would like to point out some things in more details in this comment.

1. Indeed, there are several packages for storing DNA methylation data, and we make extensive use of RnBeads's function within MAGAR. However, since MAGAR required DNA methylation _and_ genotyping data, which have to be assayed on the same samples, we decided to create a new data structure. We are not aware of any other package that is capable of storing DNA methylation and genotyping data simulteneously. Notably, we created two data structures: `methQTLInput` for processed DNA methylation and genotyping data and `methQTLResult` for storing the results of the package. The results are associations between genotypes and DNA methylation states, which also require metadata such as genomic location and information about the samples. This is why we decided for the structure that we implemented. 
2. Both data structures need to be saved to disk/loaded from disk. Since both of them use the HDF5Array R package, dedicated IO functions were required. I am not quite sure what you meant by 'inconsistent naming scheme'
3. I addressed as many of the Notes as possible.
4. Thanks for the note on Rscript, I changed it accordingly.
5. The high number of options is by design. We want to have a very flexible R package, and since the complexity of methQTL analysis is quite high, we had to include many options for the analysis. However, we used simulations to obtain reasonable default values for the parameters. A manuscript describing this in more details is currently in preparation.
6-9. You are completely right, I changed it accordingly.

@vjcitn the issue should be fixed in the most recent version.

**Comment by vjcitn** [comment]
Yes, I am now able to build the vignette.

- The link for vcftools is outdated, https://vcftools.github.io/downloads.html is correct
- The number of external utilities required (plink, vcftools, tabix, fastQTL) is unusual.  Clearly they are not all obligatory for using the package in a meaningful way, let's say to learn about it.  Can you distinguish which aspects of package use depend on which external utilities, perhaps in a table early in the vignette?
- The exercising of the software with tests/examples/vignettes could be improved?

```
> library(covr)
1/2 packages newly attached/loaded, see sessionInfo() for details.
> package_coverage()
MAGAR Coverage: 5.38%
R/cluster.R: 0.00%
R/compute_methQTL.R: 0.00%
R/correlation_blocks.R: 0.00%
R/data_import.R: 0.00%
R/GWAPMap.R: 0.00%
R/imputation.R: 0.00%
R/interpretation.R: 0.00%
R/plotting.R: 0.00%
R/utilities.R: 0.00%
R/methQTLResult-class.R: 10.97%
R/methQTLInput-class.R: 19.66%
R/options.R: 28.21%
```

I will add the external utilities to my system and continue exploring the package.

**Comment by schmic05** [comment]
Thanks @vjcitn for the comments and the nice suggestions. I added a table to the vignette and also enhanced the test coverage a bit. Let me know if you determine any further issues.

**Comment by hpages** [comment]
Thanks @schmic05 for the improvements to the package and for your answers.

Going thru my initial list of items:
 
1. Unfortunately, it seems that you indeed need to introduce your own S4 classes. Thanks for taking the time to explain. Please rename the classes so that they start with a capital letter (MethQTLInput and MethQTLResult). This is Bioconductor naming style for S4 classes.

2. IO functions `saveMethQTLResult`/`loadMethQTLResult` are for saving/loading methQTLResult objects and the names of the functions reflect that. This is a good thing. OTOH IO functions `saveMethQTL`/`loadMethQTL` are for saving/loading methQTL**Input** objects but their names do NOT reflect that. This kind of inconsistent naming tends to make life unnecessary unpleasant for your users, so should be avoided.

3. Thanks for reducing the number of `R CMD BiocCheck` notes. However one outstanding note remains about lack of examples in man pages `doImport.Rd`, `qtlLOLAPlot.Rd`, `qtlPlotAnnotationEnrichment.Rd`, and `qtlPlotSNPCorrelationBlock.Rd`. Please address. Also please address the 2 following `R CMD check` notes:
    ```
    Undefined global functions or variables:
      ..count.. Annotation Beta CpG Distance GRanges IRanges OddsRatio
      P.value PC1 PC2 Representative Rle SNP SNPDosage Size Substitution
      Type aes aes_string anno annotate anova as.formula calls chromosome
      coef cor cor.test dnorm download.file element_blank element_line
      element_text facet_grid featureData featureNames findOverlaps
      fisher.test geom_boxplot geom_histogram geom_point geom_smooth
      geom_tile geom_vline ggplot ggsave ggtitle labs lm loadRegionDB
      makeGRangesFromDataFrame mclapply median na.omit p.adjust prcomp
      queryHits read.table runLOLA scale_color_continuous
      scale_color_gradient2 scale_color_manual scale_fill_gradient2
      seqlevelsStyle<- subjectHits theme theme_bw write.table xlab ylab
    Consider adding
      importFrom("stats", "anova", "as.formula", "coef", "cor", "cor.test",
                 "dnorm", "fisher.test", "lm", "median", "na.omit",
                 "p.adjust", "prcomp")
      importFrom("utils", "download.file", "read.table", "write.table")
    to your NAMESPACE file.
    ```
    and:
    ```
    * checking for unstated dependencies in vignettes ... NOTE
    '::' or ':::' import not declared from: ‘BiocManager’
    'library' or 'require' call not declared from: ‘BiocManager’
    ```

5. Well, I only picked up one global option (`rscript.path`) that was problematic and showed you that you not only didn't need it, but also that it was counter productive to have it. So that made me wonder if you were not somehow overusing global options and maybe not necessarily always for good reasons. Now I can't go thru all the global options that the package supports but someone needs to do it, and make sure that they are all justified and safe. Let me just emphasize that, even though supporting a myriad of global options makes the software flexible, it also tends to make it harder to use, hurts reproducibility, and makes the code harder to test and maintain. Like with functions arguments, there are also some important principles attached to option semantics. One of them is _orthogonality_ which is about trying to present options that are independent from each others. In other words, an important question is: do all combinations of options make sense? If not, what option values are incompatible and are these incompatibilities documented somewhere? What happens when the user uses incompatible/conflicting options? Will the software fail gracefully with a useful error message, or will it silently return meaningless results, or will it crash? So I'm not saying that you should get rid of all the global options but I want to make sure that you are aware of the potential drawbacks of this kind of design.

8. You still have an instance of `system.file()` where `/` is used within the path components. It's in `compute_methQTL.R`.

Other issues:

10. You're using `echo=FALSE` and `eval=TRUE` for the Installation code chunk in the vignette:
![Screenshot from 2021-01-19 15-36-38](https://user-images.githubusercontent.com/8810451/105107104-2ba2f600-5a6c-11eb-98f0-935a74d96167.png)
  It needs to be the other way around.

11. The results of this code chunk are just noise:
![Screenshot from 2021-01-19 15-40-01](https://user-images.githubusercontent.com/8810451/105107275-a3712080-5a6c-11eb-9c6c-b0e081284ef7.png)
  Please hide them.
 
Thanks,
H.

**Comment by schmic05** [comment]
Hi @hpages,
Thanks a lot again for your detailed comments. I tried my very best to fix them.

1.  Thanks for pointing this out. I fixed the naming of the two classes according to the Bioconductor style.
2. I wasn't aware of this inconsistency but it totally makes sense. I changed the names of the function `saveMethQTL` and `loadMethQTL` accordingly to `saveMethQTLInput` and `loadMethQTLInput`.
3. I tried my very best to fix as many of the Notes as possible. I hope that this is now sufficient in your eyes.
4. Your comment is really helpful and I totally see your point. To improve upon that, I carefully checked all options again and deleted some of them, which are not really necessary. So I ended up with a total of 34 options, of which I see none which can be removed. To facilitate setting the options, I added a new table to the vignetted that gives an overview of the different options and that also points out potential problems. I would also like to mention that both for DNA methylation and genotyping data a myriad of different technologies exist. To support any of those, I feel that it is essential to have many options, such that the package can run with many of them This is the paradigm that I decided to use and I can understand that it is not the one that you prefer.
5. Thanks for pointing this out, I changed the function call accordingly.
10. and 11. Also thanks for pointing this out, I changed the vignette accordingly.

I hope that the software is now ready for being included in Biocondcutor. Thanks a lot for all you comments that helped to substantially improve the package.

All the best,

Michael

**Comment by hpages** [comment]
Hi @schmic05 ,

Thanks for adding the table of global options to the vignette. That's really helpful.

Please check again how you addressed item 10. I still see the output of the installation commands in the vignette. These commands should no be executed i.e. you need to set `eval` to FALSE.

H.

**Comment by schmic05** [comment]
Hi @hpages,
Thanks for raising this point; I fixed it in the most recent version.
All the best,
Michael

**Comment by hpages** [comment]
Excellent. Thanks!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/schmic05.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MAGAR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MAGAR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
