### ISSUE TITLE
Optimal p-value weighting with independent information

### ISSUE THREAD

**Issue by mshasan** [Bioconductor/Contributions#395]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mshasan/OPWeight

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mshasan** [comment]
@bioc-issue-bot Hi, is everything okay with my package? Do I need to do anything to speed up the process?

**Comment by lawremi** [comment]
First you should consider integrating more tightly with Bioconductor. For example, the DESeqResults class exists explicitly to support this type of integration, yet you just coerce it to a `data.frame`. Presumably there are other result objects, like those from limma.

**Comment by mshasan** [comment]
I really appreciate your comment. Yes, I do understand, I can improve my coding using effective tools.

**Comment by mshasan** [comment]
@lawremi I am referring to your last suggestion. Would you be able to show me the problem you pointed so that I can look at my code? Thank you, I appreciate your time and consideration.

**Comment by lawremi** [comment]
I was just referring to the example in the vignette. Ideally, the user would just pass the DESeqResult object to one of your functions, without coercing it and extracting the p-values.

**Comment by mshasan** [comment]
@lawremi I updated the vignette. I do not remember why did I coerce as.data.frame. Thank you so much.
I have a question. "Version bump required" does it mean that I need to increase package version number in the description file?

**Comment by mshasan** [comment]
@bioc-issue-bot I updated the version number by .1 in the description file and then committed. Is this the right way to do the "version bump"?

**Comment by mshasan** [comment]
@hpages I updated the version number by .1 in the description file and then committed. Is this the right way to do the "version bump"?

**Comment by lshep** [comment]
@mshasan Please make sure the [webhook is initiated](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook), then when you want a rebuild of your package on our system a version bump 0.99.1, 0.99.2 , will be requierd, so yes you were right to increase by .1.  Normally that will start a new build and you will receive a build report.   We had some trouble with our build system over the weekend so I am starting a build of your package now.  Thank you

**Comment by mshasan** [comment]
@bioc-issue-bot I updated bioc-devel subscription. There should be no error now.

**Comment by mshasan** [comment]
@lshep Is there anything that I need to do to fix these warnings? I do not see these warnings always when I perform R CMD check

**Comment by mshasan** [comment]
@lshep I do not see any warnings except three minor notes!

**Comment by lshep** [comment]
@hpages will review this package;  I have been assigned to review the other package you submitted.

**Comment by mshasan** [comment]
@hpages I do not find any warnings except three minor notes!

**Comment by mshasan** [comment]
@hpages I do not find any warnings except three minor notes!

**Comment by mshasan** [comment]
@hpages would you please look at my package seriously? I have been trying to contact you several times but you do not respond me. It looks very unprofessional. If you do not have time please assign someone else.  It has been 12 days and not a single time you responded my message!!!!!!!!!!

**Comment by grimbough** [comment]
You can get rid of the warnings during `R CMD build` by deleting the `inst/doc` folder and its contents.  I presume this is an outdated duplicate of the the version in `vignettes` folder, and `vignettes` is the appropriate place for one copy.

**Comment by mshasan** [comment]
@grimbough Thank you for your valuable suggestion

**Comment by vobencha** [comment]
I'll try to get a review done for this by Monday.
Valerie

**Comment by mshasan** [comment]
@vobencha Thank you so much

**Comment by vobencha** [comment]
Hi,

Nice job with the man pages and documentation. A few comments and suggestions below.

1) DESCRIPTION / NAMESPACE
Packages in 'Depends' are attached to the search path when the primary package is loaded (i.e., all functions in that package are available). For this reason, packages in 'Depends' are usually fully imported in the NAMESPACE, e.g., import(MASS).

    If you only need a couple of functions from MASS, qvalue and tibble then they should be in 'Imports' and not 'Depends'.

2) opw.Rd man page
No need to load a package that you've listed in 'Depends'.  qvalue will be automatically loaded when OPWeight is. Please remove this from the example section:
```
  library(qvalue)
```

3) data type in \value and \arguments in man pages
I'll use weight_binary.Rd as an example but this applies to all man pages.

    Please specify the data type for each argument and the value, e.g., is 'alpha' a vector , matrix or scalar? logical, numeric or character?
```
  \item{alpha}{significance level of the hypotheis test}
```
Is 'weight' a vector, matrix or scalar? logical, numeric or character?
```
  \value{
  \code{weight} normalized weight of the tests for the binary case
  }
```
4) vignette files
I think the \vignette directory should only contain the .Rmd and .bib files.
~/repos/git/software/OPWeight/vignettes >ls
bibliography.bib  OPWeight_files  OPWeight.R
OPWeight_cache    OPWeight.html   OPWeight.Rmd

    Please remove these or explain why you think you need them:
    OPWeight_files/
    OPWeight_cache/
    OPWeight.html
    OPWeight.R

5) vignette code
- Show how to to download/install OPWeight with biocLite("OPWeight")
- Load OPWeight at the top of the vignette. This will load the packages in 'Depends' so you can then remove these:
```
library(tibble)
library(qvalue)
library(MASS)
```
6) NEWS
This file should be at the same level as R/, man/ and vignettes/, not in inst/NEWS. Please move it up and remove the inst/ directory.

7) size
The built tarball should be <= 4MB on disk:
http://www.bioconductor.org/developers/package-guidelines/#correctness

    We need to do some trimming:
~/repos/git/software >du -h OPWeight_0.99.9.tar.gz
58M    OPWeight_0.99.9.tar.gz

Let me know if you have any questions.

Valerie

**Comment by mshasan** [comment]
@vobencha Thank so much you for your insightful suggestions. I will update as soon as possible and let you know if I have any questions.

**Comment by mshasan** [comment]
@vobencha I have few questions regarding your suggestions:

Point 2 and 5: I removed MASS, tibble, and qvalue from the Depends and added to Imports. Can I still remove from the opw.Rd and vignette code

```{r}
library(qvalue)
library(tibble)
library(MASS)
```

Point 7: How do I reduce the size? I checked the folders and found that the actual package is less than 1MB but the git folder is taking all the spaces.

Thank you

**Comment by mshasan** [comment]
@vobencha Can you look at now? I fixed all the problems.

**Comment by vobencha** [comment]
Hi,

Thanks for making the changes.

Addressing comments in:
https://github.com/Bioconductor/Contributions/issues/395#issuecomment-311179412

- Point 2 and 5: I removed MASS, tibble, and qvalue from the Depends and added to Imports. Can I still remove from the opw.Rd and vignette code

    Using 'package A' as an example:

    When package A is in Imports, all the functions exported from package A are avaialble to your package. They aren't, however, available to the user in their workspace. If the vignette or man pages directly call a function from package A, e.g., a class extractor, then you need to load that package in the vignette or man page. Loading the package (i.e., calling library()) puts the package on the serach path and makes all functions in package A available to your package and the user workspace. Having a package in Depends is essentially the same as calling library().

    If you're not sure whether or not you're calling functions from qvalue, tibble and MASS, I would try removing the library() statements you have in the man pages and vignette. If you get an error then you can put the library() statements back. If it's necessary for the user to have access to functions from package A to manipulate your objects then I would leave package A in Depends and then you can certainly remove the library() statements.

- Point 4: Is there any automatic way to remove these files/folders from the vignette folder? I do not want to keep these files however these files are generated automatically.

    Martin pointed you to the solution in this post but it looks like you still have cache=TRUE ... ?
https://stat.ethz.ch/pipermail/bioc-devel/2017-June/011144.html

- Point 7: How do I reduce the size? I checked the folders and found that the actual package is less than 1MB but the git folder is taking all the spaces.

    You need to clean up your git history. Martin suggested a link in his response
https://stat.ethz.ch/pipermail/bioc-devel/2017-June/011144.html

    Another post about the same issue:
https://blog.ostermiller.org/git-remove-from-history

- Additional vignette clean up
Please remove the code that is not evaluated, e.g.,
```
# # for the binary effects estiamted median effects
# mean_testEffect = median(test_effect, na.rm = TRUE)
# mean_testEffect
# mean_filterEffect = model$coef[[1]] + model$coef[[2]]*mean_testEffect
# mean_filterEffect
```
Valerie

**Comment by mshasan** [comment]
@vobencha Can I keep cache=TRUE in the vignette then delete the cache folders manually; otherwise the package faces TIMEOUT problem?

**Comment by vobencha** [comment]
The build system will build the package each night so cache=TRUE with a manual file delete is not an option. I see Martin wrote you back on bioc-devel with suggestions for identifying code inefficiencies - that would be the best advice to take.
Valerie

**Comment by mshasan** [comment]
@vobencha I followed your suggestions. I believed the package would be okay now. I also would like to keep .R and .html file in the vignette folder because this will give an instantaneous idea and the benefits of the package to the general audience before installing it.

**Comment by vobencha** [comment]
I understand you want to provide a 'real time' view - that makes sense. Unfortunately the .R and .pdf files run the danger of becoming stale unless you remember to update them whenever the .Rmd file changes. If you want to keep them, please add the .R and .html to an OPWeight/.Rbuildignore file so they are ignored during R CMD build / check.
Valerie

**Comment by mshasan** [comment]
@vobencha Thank you for your recommendations. I updated the package accordingly.

**Comment by vobencha** [comment]
Thanks for making the changes - the package is approved. We still have the data package to review:https://github.com/Bioconductor/Contributions/issues/396
 I'm guessing you'll focus on that one next?
Valerie

**Comment by mshasan** [comment]
@vobencha Thank you so much. I appreciate your time and recommendations. Now I will review #396.
