### ISSUE TITLE
iterClust

### ISSUE THREAD

**Issue by hd2326** [Bioconductor/Contributions#449]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hd2326/iterClust

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
Bioconductor packages require a comprehensive vignette, biocViews, and strongly recommend that the user interface is interoperable with [appropriate Bioconductor data classes][1]. Your package does not have these features, and so will not be reviewed.

[1]: http://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by hd2326** [comment]
Hi,

Just fixed the problems and please see the updates here:

https://github.com/hd2326/iterClust/

Thank you very much!

Ding

**Comment by mtmorgan** [comment]
See 'Writing R Extensions' for information on vignettes -- the Rnw or Rmd file belongs in the vignettes/ directory, the build products (.R and .pdf) do not belong in the repository. Instead of accepting a matrix, users will expect to be able to provide a SummarizedExperiment and / or ExpressionSet object.

**Comment by hd2326** [comment]
fixed...

**Comment by hd2326** [comment]
@mtmorgan 

Hi Martin,

Just want to check with you the current status of the package. Anything I need to do for it?

Thank you very much!
Ding

**Comment by mtmorgan** [comment]
@hd2326 sorry I missed / misinterpreted the 'fixed' comment. I re-opened the issue and approved it. Th esingle package builder should try to build your package and report on progress. When the package builds without problems, Marcel will review it.

**Comment by hd2326** [comment]
I build the package on my own Linux and Windows and there's no problem... What should I do in response to the build report?

Thank you very much!
Ding

**Comment by mtmorgan** [comment]
Correct the problems! The windows builder indicates that you're not subscribed to the bioc-devel mailing list or to the support site. Do that. The linux / mac issue is a little obscure, but it says somehow that the vignette is not correct on those platforms. For instance at vignette/introduction.rnw line 319 character 271 there is an extra `}`

**Comment by hd2326** [comment]
1. bioc-devel mailing list subscribed
2. I think I fixed the introduction.tex to introduction.pdf problem. Now "Running pdflatex.exe on introduction.tex...completed" and introduction.pdf successfully created.
3. remove /inst/doc/ so there should be no warnings.

**Comment by mtmorgan** [comment]
If you committed to your github repository, it didn't trigger a build. You forgot to increment the version number (to 0.99.1) and you probably did not (correctly) enable the [web hook](https://github.com/Bioconductor/Contributions#adding-a-web-hook).

**Comment by hd2326** [comment]
Finally...

So now the package should be reviewed by @LiNk-NY ?

**Comment by LiNk-NY** [comment]
Hi @hd2326,
Yes, I will be reviewing your package in the next few days.
Thank you @mtmorgan for following up on the necessary prerequisites.

Regards,
Marcel

**Comment by hd2326** [comment]
Thank you guys!

**Comment by LiNk-NY** [comment]
My apologies for the delay. @hd2326 
I am currently reviewing your package. 
Regards,
Marcel

**Comment by hd2326** [comment]
No worry Marcel @LiNk-NY. Please let me know if there's any updates!

Best,
Ding

**Comment by LiNk-NY** [comment]
Hi Hongxu Ding, @hd2326 

Thank you for submitting to Bioconductor.
Your package is compact and thus easier to maintain. 
There were a few issues that should be addressed. 
Please see the review below. 

If you have any questions, please let me know. 

Best regards,
Marcel 

---

# iterClust #449

## DESCRIPTION

* Please add the relevant links to the GitHub repository
* Remove the date (not needed)
* Include a depends field for R (>= 3.4.1)

## NAMESPACE

* Looks good

## R

* Please properly indent your scripts and other written documents,
make sure they do not surpass a width of 80 characters

* The `iterClust` function apprears to have a complicated interface which may
be difficult for the user. The use of this many functionals will lower
useability

* Please provide a set of default functions for `iterClust`

* Rename the function arguments and remove the `fun` tag from them. The
argument names should be descriptive and documented well enough  for users to
be able to see that they are functional arguments.

* Observe where you can remove unnecessary functional arguments such as
`featureSelectfun` which may be a logical vector applied to select features

* Test class membership with the `methods::is` for S4 or `is.*` functions
such as `is.matrix` and `is.data.frame` for S3 classes 

* Avoid assigning objects to function names such as `c <- list()`. `c` is a
function, please use a different name

* Avoid using `sapply` and go for the more robust `lapply` and `vapply`
functions 

* Break up the iterClust function where possible into smaller functions so
that it is more manageable

* Avoid the use of `1:n` sequence generation, use the more robust `seq_len`
or `seq_along`

## vignettes

* It's apparent that you're reusing the examples in your main function for
the vignette
* Please showcase the use of your function in your package in the main
vignette
* The "Run iterClust" shows that your nested list structure is unwieldly and
it would require a user to dig into the list to find the necessary elements
* The `iterClust` function should return an output with more structure

## Other

* Please remove the `thumbs.db` from the package folder and add it to the
`.gitignore`
* Please fix the errors in the examples and the vignette:

```
## example
Error in silhouette.default(clust[[i]], dist) : 
  object 'sildist' not found

## vignette
Error: object 'sildist' not found
```

If you did fix this error, please bump the package version.

**Comment by hd2326** [comment]
Dear Marcel @LiNk-NY ,

Thank you for your comments! I made the following changes:

DESCRIPTION
•Please add the relevant links to the GitHub repository
**Do you mean release branch? I synchronized release with master...**
•Remove the date (not needed)
**Done**
•Include a depends field for R (>= 3.4.1)
**Done**

NAMESPACE
•Looks good

R

•Please properly indent your scripts and other written documents,
 make sure they do not surpass a width of 80 characters
**Done**

•The  iterClust  function apprears to have a complicated interface which may
 be difficult for the user. The use of this many functionals will lower
 useability
**I provided default functions so that iterClust() is easier to use. Also, the definition of default functions and their documentations will provide guideline for users to customize their own functions.**

•Please provide a set of default functions for  iterClust 
**Done**

•Rename the function arguments and remove the  fun  tag from them. The
 argument names should be descriptive and documented well enough for users to
 be able to see that they are functional arguments.
**Done**

•Observe where you can remove unnecessary functional arguments such as
 featureSelectfun  which may be a logical vector applied to select features
**I want to make the iterClust framework as flexible as possible. That is to say, for instance, how to select features is completely determined by the users. This is because there're many widely used ways in selecting features, e.g. all features (used in iterClust by default), highly variable features etc... and it's not reasonable to force users to just use one of them by asking whether do feature selection or not.**

**Based on my experience in bioinformatics analysis, especially single cell transcriptomic analysis,  I think all the functions required by iterClust() are necessary therefore I would prefer we keep everything.**

•Test class membership with the  methods::is  for S4 or  is.*  functions
 such as  is.matrix  and  is.data.frame  for S3 classes
**Done**

•Avoid assigning objects to function names such as  c <- list() .  c  is a
 function, please use a different name
**Done**

•Avoid using  sapply  and go for the more robust  lapply  and  vapply 
 functions
**Done**

•Break up the iterClust function where possible into smaller functions so
 that it is more manageable
**The structure of iterClust() is a while loop, therefore I think it's really hard to break it into smaller functions. However I use many externally-defined functions, which are embedded in the iterClust() as a whole with strictly defined input/output to make the framework more manageable.**

•Avoid the use of  1:n  sequence generation, use the more robust  seq_len 
 or  seq_along 
**Done**

vignettes
•It's apparent that you're reusing the examples in your main function for
 the vignette
**I still use the same dataset, but remove some non-essential codes for performing iterClust() in the main function.**
•Please showcase the use of your function in your package in the main
 vignette
**Done**
•The "Run iterClust" shows that your nested list structure is unwieldly and
 it would require a user to dig into the list to find the necessary elements
•The  iterClust  function should return an output with more structure
**The iterClust() output is organized as a list, recording 1) features used to generate clusters and 2) observations belong to each cluster by iteration. Thereby we can keep the trace of iterative clustering, which is critically important. Therefore I would prefer keep the current output format.**

Other
•Please remove the  thumbs.db  from the package folder and add it to the
 .gitignore 
**Done**
•Please fix the errors in the examples and the vignette:
## example
Error in silhouette.default(clust[[i]], dist) : 
  object 'sildist' not found

## vignette
Error: object 'sildist' not found
**Done**


Thank you very much!
Ding

**Comment by hd2326** [comment]
@LiNk-NY 

•Please add the relevant links to the GitHub repository

I just added ssh keys, which I didn't realized yesterday...

Thank you Marcel!
Ding

**Comment by LiNk-NY** [comment]
Hi Ding, @hd2326 
You can add these GitHub repository and BugReports links in the `DESCRIPTION`: 
```
URL: https://github.com/hd2326/iterClust
BugReports: https://github.com/hd2326/iterClust/issues
```

Response: 

<blockquote>
• Observe where you can remove unnecessary functional arguments such as
featureSelectfun which may be a logical vector applied to select features

<strong> I want to make the iterClust framework as flexible as possible. That is to say, for instance, how to select features is completely determined by the users. This is because there're many widely used ways in selecting features, e.g. all features (used in iterClust by default), highly variable features etc... and it's not reasonable to force users to just use one of them by asking whether do feature selection or not. </strong>
</blockquote>

I just meant that you can simplify the function by allowing the user to select features **outside** of the function. The function already does too much and adding a functional argument does little for usability.
That is why I suggested this argument be an index or logical type of vector that will allow the user to select features.
Another option is to adjust the function so that it computes on all the features by assuming that the user has selected them beforehand.

Regards,
Marcel

**Comment by hd2326** [comment]
@LiNk-NY 

Thank you Marcel! I added the URLs and updated the repository.

About the feature selection, the power of iterClust is the users can select different features at different iterations. For instance, we have two major single cell populations, A and B, defined by gene set #1. B has two subpopulations B1 and B2, defined by gene set #2. To better illustrate the heterogeneity here, it's better practice to use #1 to separate A and B in 1st iteration, and further use #2 to separate B1 and B2 in the 2nd iteration (actually some papers used this kind of idea, e.g. Usoskin, Nature Neuroscience, 2015, just they didn't provide a statistical framework like iterClust to do this).

Furthermore, #1 and #2 should be selected in an unsupervised manner. For instance, in each iteration we use over-dispersing genes (Brennecke, Nature Methods, 2013). Therefore it's better practice to define a function, which can be used in each iteration, providing rules in feature selection.

Therefore I'd prefer we keep featureSelect function as an input of iterClust framework.

Best,
Ding

**Comment by LiNk-NY** [comment]
Hi Ding, @hd2326

Thank you for making those changes. Your package has been accepted. 

Please ensure that your package is following Bioconductor guidelines as
you go forward. You can also look into using [MangoTheCat/goodpractice](https://github.com/MangoTheCat/goodpractice) as you maintain your
package.

Thank you for submitting to Bioconductor.

Best regards,
Marcel

**Comment by hd2326** [comment]
@LiNk-NY Great! Thank you very much Marcel!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hd2326.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"iterClust\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/iterClust

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
