### ISSUE TITLE
phantasus

### ISSUE THREAD

**Issue by baba-beda** [Bioconductor/Contributions#459]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ctlab/phantasus

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment]
No need for Author: or Maintainer: field when Authors@R used; these are created with `R CMD build ...`.

The vignette should contain fully evaluated code illustrating package use, but just contains images.

hpages will provide a full review.

**Comment by hpages** [comment]
Hi Daria,

I installed libapparmor-dev on the build machine, a requirement for the sys package (from CRAN) which phantasus indirectly depends on (via the opencpu package). With this, phantasus can now be installed but `R CMD check` still produces the following error:
```
hpages@latitude:~$ R CMD check phantasus_0.99.2.tar.gz
* using log directory '/home/hpages/pkgreviews/phantasus.review/phantasus.Rcheck'
* using R version 3.4.0 Patched (2017-04-26 r72630)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file 'phantasus/DESCRIPTION' ... OK
* this is package 'phantasus' version '0.99.2'
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package 'phantasus' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... NOTE
Unexported objects imported by ':::' calls:
  'GEOquery:::getDirListing' 'opencpu:::rookhandler'
  See the note in ?`:::` about the use of this operator.
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of 'data' directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ... OK
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  6: getGSE(name, destdir)
  7: suppressWarnings(getGEO(GEO = name, destdir = destdir, AnnotGPL = TRUE))
  8: withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning"))
  9: getGEO(GEO = name, destdir = destdir, AnnotGPL = TRUE)
  10: getAndParseGSEMatrices(GEO, destdir, AnnotGPL = AnnotGPL, getGPL = getGPL)
  11: parseGSEMatrix(destfile, destdir = destdir, AnnotGPL = AnnotGPL, getGPL = getGPL)
  12: readLines(fname)
  13: file(con, "r")
  
  testthat results ================================================================
  OK: 13 SKIPPED: 0 FAILED: 1
  1. Error: loadGEO finishes with result (@testloadGEO.R#6) 
  
  Error: testthat unit tests failed
  Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking running R code from vignettes ...
   'developer-tutorial.Rmd' using 'UTF-8' ... OK
   'phantasus-tutorial.Rmd' using 'UTF-8' ... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 1 ERROR, 1 NOTE
See
  '/home/hpages/pkgreviews/phantasus.review/phantasus.Rcheck/00check.log'
for details.
```
Please address at your earliest convenience.
Thanks,
H.

**Comment by hpages** [comment]
Hi Daria,

Thanks for fixing the `R CMD check` error.

I started to look at the package but I only have very little feedback for now because I'm stuck (see issue 3 below):

1. The phantasus-tutorial vignette has no title, no author, and no date. Please address.

2. The vignette and man pages say that an instance of phantasus application can be started with:
```
  servePhantasus('0.0.0.0', 8000, cacheDir = file.path(getwd(), 'cache'))
```
Does the command really need to be so complicated? Please use sensible argument defaults so that the user doesn't need to specify these criptic arguments. Ideally, calling `servePhantasus()` with no arguments should work for most people. Specifying arguments should only be needed for people with a non-standard setup or with special needs.

3. What should I expect after I call `servePhantasus()`? The vignette doesn't say. I guess I should see some kind of GUI popping up somewhere but I don't see anything so I can't continue. Also the `servePhantasus()` call is not returning either and doesn't print anything. Would be nice it was printing some kind of diagnostic message in case something is wrong with my setup.

4. The biocViews field only contains GeneExpression, despite the package being also about Visualization, Clustering, and maybe more. Make sure to add any term that is relevant to your package.

Thanks,
H.

**Comment by baba-beda** [comment]
Hi Herve,

We have addressed all of the issues from your feedback:
1. The phantasus-tutorial now has the appropriate header.
2. `servePhantasus` now can be run with the default configuration. Information about the advanced usage has been added to the tutorial. 
3. `servePhantasus()` by default opens browser with the local Phantasus url (http://localhost:8000/ by default). A corresponding message is printed to the console. 
4. The biocViews have been extended.

However, we stuck with a BiocCheck error concerning runnable examples. We have only four exported functions, with `servePhantasus` being one of them. At the moment it runs the http-server in a foreground mode until it’s interrupted. So, we can’t make a running example as it will hang at check stage. We are not sure what is the best way to deal with this: on one hand we can add an option for `servePhantasus` to be run at the background, on the other hand we don’t think it’s useful from user experience point of view. Can you recommend us something in this regard?

Thank you,
Daria.

**Comment by hpages** [comment]
Hi Daria,
Thanks for addressing these issues. I agree that adding an option for `servePhantasus()` to be run in the background wouldn't be useful from user experience point of view. Let's ignore this BiocCheck complaint for now. I'm going to take a 2nd look at the package.
H.

**Comment by hpages** [comment]
Hi Daria,

Thanks for the recent changes and improvements. `servePhantasus()` now starts the server and I was able to use it. Please find my feedback below.

Best,
H.

1. Vignette seems to be out-of-sync with the current phantasus e.g. after loading GEO dataset GSE53986, only columns `Gene symbol` and `Gene ID` get displayed but the vignette shows columns `id`, `Gene symbol`, and `UniGene symbol`. Also the vignette shows a `treatment` line below the `geo_accession` line in the matrix header but I only get the `geo_accession` line.

2. A quick note about what the GSE53986 dataset is about would be nice.

3. You use the term "rescale" in the vignette but that operation is accessed via the "Adjust" feature. Why not be consistent? Generally speaking using consistent terms is easy and adds a lot of clarity to a software interface and documentation. Also, isn't this operation usually called "normalization"?

4. It seems that a new tab is created after some transformations e.g. after the "rescale" step but not after the "collapse" step. Why does this happen with some transformations and not with others? Is this explained somewhere?

5. The user should be able to change his/her mind and try different things. How can one undo a transformation? I can see that in the case of the "rescale" operation, one can click on the tab corresponding to the original step of the dataset and try a different "rescale" operation. This will
produce a new tab with the result of this new "rescale" operation. The user can then compare with the result of the previous "rescale" operation by switching between the 2 tabs. However, that only works for transformations that produce a new tab. How can one try different "collapse" transformations and compare them in a convenient way?

6. Another issue with managing the history of transformations via tabs is that the label that gets displayed in the tabs is pretty obscure (e.g. GSE53986-GPL1261 after normalization). What's the logic behind this labelling scheme? Is this explained somewhere? Also, the label seems to be the same whatever "rescale" method I use which is confusing and not helpful, especially in the case where one tries different "rescale" operations to compare them.

7. Placing the cursor over a tab displays the dimensions of the matrix that is displayed in the tab. Note that this information is not updated after one performs the "collapse" step, so ends up being incorrect. It seems that this problem would best be avoided by having the "collapse" step create a new tab like the "rescale" step does.

8. After defining the "top filter" and entering 12000 in the N box, 12001 genes are kept.

9. Some cryptic output is produced in the R session each time one performs an operation in the phantasus GUI e.g.
```
...
[2017-10-09 10:50:11] POST /ocpu/library/phantasus/R/loadGEO
[2017-10-09 10:50:12] GET /ocpu/tmp/x015dc00637/messages/text
[2017-10-09 10:50:12] GET /ocpu/tmp/x015dc00637/R/.val
[2017-10-09 10:50:12] GET /ocpu/tmp/x015dc00637/R/.val/print
[2017-10-09 10:50:13] GET /ocpu/tmp/x015dc00637/files/gse2fe64c793a43.bin
[2017-10-09 10:50:14] POST /ocpu/library/phantasus/R/createES
[2017-10-09 10:50:24] POST /ocpu/library/phantasus/R/createES
[2017-10-09 10:50:53] POST /ocpu/library/phantasus/R/createES
[2017-10-09 11:17:09] POST /ocpu/library/phantasus/R/createES
[2017-10-09 11:18:26] POST /ocpu/library/phantasus/R/createES
...
```
I'm not convinced that this output is very useful to the average user. Could it be replaced with something more sensible by default, or reduced to important warnings and/or errors only, or disabled entirely? Advanced users might want to be able to control this via some extra arguments to `servePhantasus()`.

10. How does one come back to the Phantasus startup page (e.g. to open a new dataset) without closing the current tabs? In other words, how does one work with several datasets at a time?

**Comment by baba-beda** [comment]
Hi Herve,
Thank you for your feedback. We addressed all of your comments:

1. We updated the vignette, now it reflects the current GUI of the Phantasus application.
2. Short description about GSE53986 and a link to this dataset were added in the beginning of the workflow example.
3. Now the term “normalize” is used consistently in the description of the normalization step.
4. In the current version any “destructive” function like Adjust or Collapse shows the result in a new tab, this way you can easily compare results or revert changes.
5. Same as above.
6. The tab being renamed was a bug. Now the name of the dataset stays fixed, unless it is changed manually by the user (how to rename a tab was added to the vignette).
7. Collapse tool now creates a new tab, so this bug was eliminated.
8. This happens because multiple genes can have the same value of the parameter used for filtering, so more than exact number of genes can be kept. We added corresponding info to the vignette.
9. Output produced by internal OpenCPU functions is captured now, so this log of requests won’t be displayed to the user.
10. New datasets can be opened via File menu. We’ve added corresponding information to the vignette. 

Thank you.
Best wishes,
Daria

**Comment by hpages** [comment]
Hi Daria,

Thanks for the update. Some of the items reported previously are partially addressed only. See below. There is also a couple of additional issues.

Regards,
H.

(1) Note that the vignette still shows a `treatment` line below the `geo_accession` line in the matrix header but I don't see that in my own session.

(4) The difference between “destructive” and non-destructive functions would need to explained **in the vignette**. Otherwise the user (like me) will still be confused about why some operations create a new tab and others don't.

(6) Thanks for adding how to rename a tab to the vignette. By default new tabs are still created with the same name as the parent tab even though the contents are different. This is not optimal from a usability point of view. Could this be modified?

(10) OK but what if I want to come back to the startup page to pick up one of the data sets listed there?

Other issues:

11. Typo in "The result will appear as additional row annotation". Should be "column annotation".

12. I tried to sort the rows by ascending mean expression but after pressing OK nothing happens. If I click on Cancel, I get an Error (Oops, something went wrong. Please try again.) Then I need to click several times on the cross in the top right corner of the error window before I can get rid of it.

**Comment by hpages** [comment]
Hi Daria,
Just a reminder that the BioC 3.6 release is coming soon and that we'll stop adding new packages to it in a couple of days.
Regards,
H.

**Comment by hpages** [comment]
Hi Daria,

Do you intend to follow up on this submission? If I don't hear from you before end of January, I'll close this issue.

Thanks,
H.

**Comment by assaron** [comment]
Hi Herve,

We're going submit a new version by the end of December. As we didn't make it for 3.6 release we took time to improve some other things as well.

Best,
Alexey

**Comment by hpages** [comment]
Hi Alexey, thanks for the update.  H.

**Comment by assaron** [comment]
Hello Herve,

We have updated the package: made several bug fixes and minor improvements, added a new analysis method (via data submission to an external web-service) and reworked the vignette.

The two warnings that are left are technical: 
1. Dependency on R >= 3.5, this could be easily fixed.
2. Size of one of the JavaScript files is greater than 5MB. I'm not sure how to better deal with it. Hope here for your input.

To answer your specific comments:

> (1) Note that the vignette still shows a treatment line below the geo_accession line in the matrix header but I don't see that in my own session.

Sadly, we can't reproduce this. `treatment` annotation should indeed be shown. May be there was some incompatibility with GEOquery version.

> (4) The difference between “destructive” and non-destructive functions would need to explained in the vignette. Otherwise the user (like me) will still be confused about why some operations create a new tab and others don't.

We added the following to the vignette:

> All operations that modify gene expression matrix (such as adjustment, subsetting and several others) create a new tab. This allows to revert the operation by going back to one of the previous tabs.

Hope that explains the idea. However, we wouldn't give a strict definition, as the list of operations creating a new tab can be modified depending on the user experience.

> (6) Thanks for adding how to rename a tab to the vignette. By default new tabs are still created with the same name as the parent tab even though the contents are different. This is not optimal from a usability point of view. Could this be modified?

We agree that multiple tab with the same name could be confusing. On the other hand, it is not clear how the names could be set automatically: for example, appending a suffix for each operation will quickly lead to long unreadable names.

> (10) OK but what if I want to come back to the startup page to pick up one of the data sets listed there?

There is a clickable link _Preloaded datasets_ in the _File/Open_ menu.

> Typo in "The result will appear as additional row annotation". Should be "column annotation".

This is not a typo. While this a column, it is an annotation for rows (genes).

> I tried to sort the rows by ascending mean expression but after pressing OK nothing happens. If I click on Cancel, I get an Error (Oops, something went wrong. Please try again.) Then I need to click several times on the cross in the top right corner of the error window before I can get rid of it.

Yes, it was a bug. It should be working now.

Thanks,
Alexey

**Comment by assaron** [comment]
Hi Herve,

We've fixed the build warnings, added few minor features and fixed few bugs. 

The Linux build now works fine. OS X build fails with error "package webutils was installed by an R version with different internals; it needs to be reinstalled for use with this R version". I believe I can't do anything about it aside for restarting the build later. Windows build (CHECK part) is said to be timed out, but the actual logs seems to be fine.

**Comment by assaron** [comment]
Got it. There are no binaries for opencpu (and webutils) for OS X and
r-devel. Windows time out is still a mystery though.

On Feb 18, 2018 11:06, "bioc-issue-bot" <notifications@github.com> wrote:

Dear Package contributor,

This is the automated single package builder at bioconductor.org.

Your package has been built on Linux, Mac, and Windows.

On one or more platforms, the build results were: "skipped, TIMEOUT, ERROR".
This may mean there is a problem with the package that you need to fix.
Or it may mean that there is a problem with the build system itself.

Please see the build report
<http://bioconductor.org/spb_reports/phantasus_buildreport_20180218030607.html>
for more details.

—

You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Bioconductor/Contributions/issues/459#issuecomment-366499266>,
or mute the thread

**Comment by assaron** [comment]
@hpages I've fixed Windows build timeout problem. OS X fails due to absence of r-devel binary builds for OS X in CRAN. I understand that it can take a while until such builds appear. In the meantime I'm running checks in Travis and everything works OK there for OS X and R-devel: https://travis-ci.org/ctlab/phantasus/builds/346976996 So, hopefully the OS X build problem can be ignored for now.

Waiting for your reply,
Alexey

**Comment by hpages** [comment]
Hi @assaron ,
Thx for the update. I manually installed opencpu yesterday on our Mac builder merida2. You could try to bump phantasus version to trigger a new build so we'll be able to see how it does on merida2. I'll take a look at this latest version of the package in the next couple of days.
Best,
H.

**Comment by assaron** [comment]
The error is still "Error : package webutils was installed by an R version with different internals; it needs to be reinstalled for use with this R version"

**Comment by hpages** [comment]
@lshep Hi Lori, I manually installed webutils and opencpu on merida2 a couple of days ago and I can load them in an interactive R session:
```
library(webutils)
library(opencpu)
Loading config from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/opencpu/config/defaults.conf
Loading config from /Users/biocbuild/Library/Application Support/opencpu/user.conf
Welcome to OpenCPU!
```
Could it be that the Single Package Builder is using a stale installation of webutils? If so, any chance it can be removed?
Thanks,
H.

**Comment by lshep** [comment]
There was a second install in a package specific library path -  I have removed it and kicked off a new build.  The build report should be posted soon.

**Comment by assaron** [comment]
Lori, thanks! 

There are still seems to be problems with dependencies though... Is there any way to get the full error log from tests? The actual error message is missing now:
```
Last 13 lines of output:
  10: tryCatch(loadNamespace(name), error = function(e) stop(e))
  11: tryCatchList(expr, classes, parentenv, handlers)
  12: tryCatchOne(expr, names, parentenv, handlers[[1L]])
  13: value[[3L]](cond)
  
   testthat results  
  OK: 34 SKIPPED: 0 FAILED: 5
  1. Error: limmaAnalysis finishes with result (@testlimmaAnalysis.R#5) 
  2. Error: limmaAnalysis works when there is only one phenotype attribute (@testlimmaAnalysis.R#12) 
  3. Error: loadGEO finishes with result (@testloadGEO.R#8) 
  4. Error: loadPreloaded loads file with just one ExpressionSet (@testloadPreloaded.R#25) 
  5. Error: loadPreloaded loads file with list of ExpressionSets (@testloadPreloaded.R#33) 
```

I understand they should be available here: /Users/pkgbuild/packagebuilder/workers/jobs/459/phantasus_20180308072603/phantasus.Rcheck/00check.log

**Comment by lshep** [comment]
It looks like protolite also needs to be updated -  I'll remove this package too and see if the fresh install will help

**Comment by assaron** [comment]
@lshep thank you!

**Comment by hpages** [comment]
That did the trick! Thx @lshep

**Comment by hpages** [comment]
Hi @assaron ,

Thanks for addressing all the issues I reported earlier. phantasus is in good shape and ready to be added to Bioconductor. I found 2 minor issues while testing this latest version (0.99.31). They are not show stoppers so I'll open issues on GitHub and you can address them later. I'm labelling the package as accepted.

Thanks for contributing to Bioconductor.

Best,
H.

**Comment by assaron** [comment]
Thank you, Herve!

**Comment by mtmorgan** [comment]
Hi -- the submodule in inst-raw is causing problems for us cloning this package to our git repository. Conceptually, the Bioconductor git repo git.bioconductor.org:packages/phantasus is meant to be the canonical location of source code for the package. But having a submodule implies that some code is not in the Bioconductor git repository. My first inclination is to suggest that the submodule be removed from the master branch (if the submodule is somehow intermediate code not essential to package function) or fully materialized. Thoughts?

**Comment by assaron** [comment]
Hello Martin,

Yes, I can remove the submodule from the master branch. It is useful in the development process, but, indeed, a lot of tools lack support for git submodules (not only Bioconductor). So, everything required for the package installation (and partial development) is available in the core repository. 

Should I proceed? Should I also bump the version after update?

**Comment by mtmorgan** [comment]
yes proceed and with a version bump. Thanks!

**Comment by assaron** [comment]
Done. Version 0.99.33 should be good.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/baba-beda.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"phantasus\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/phantasus

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform
