### ISSUE TITLE
runibic: UniBic biclustering algorithm for R

### ISSUE THREAD

**Issue by athril** [Bioconductor/Contributions#515]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/athril/runibic

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment]
Integrate with Bioconductor by providing functions that accept SummarizedExperiment. Provide a vignettte that more comprehensively and realistically illustrates functionality, e.g., using an existing Bioconductor experiment data package. Include interpretation of function output, perhaps comparing to similar algorithms. The code chunks (other than illustrating package installation) must be runnable.

Make the changes above and post a comment here; your package will then be moderated for cross-platform build and check, and added to the review queue.

**Comment by athril** [comment]
Updated version to 0.90.1
Please contact me in case of any question / additional requirements.

**Comment by mtmorgan** [comment]
Thanks; the version number should be 0.99.0, bumped to 0.99.1, 0.99.2, etc; it is at 0.90.0 ('90' is wrong, and with no version bump with recent commit)

**Comment by athril** [comment]
Oops.. a typo. Bumped to 0.99.1.

**Comment by hpages** [comment]
Hi @athril 
Please address the errors reported by the Single Package Builder and bump the version of your package in order to trigger a new build. Thanks!
H.

**Comment by athril** [comment]
Within the last couple of commits we've further optimized the performance of the method. 
The algorithm in our package work a couple of times faster than the original version of the algorithm. Would you consider the package for the new release of Bioconductor?

**Comment by hpages** [comment]
Hi Patryk,

Thanks for your submission. The documentation of the runibic package needs to be improved significantly. Please see my detailed feedback below.

Regards,
H.
 
1. A stale object file (`GlobalDefs.o`) is polluting the `runibic/src/` folder and breaks doing `R CMD INSTALL` directly on the package source tree. Please remove it.

2. `runibic-vignette.R` does not qualify as a vignette and has no place in the `runibic/vignettes/` folder. A valid vignette should be a Sweave (`.Rnw`) or R markdown (`.Rmd`) document. Is this a leftover of some early vignette draft? Do you still need it? Please either remove it, or turn it into a real vignette, or merge it into the existing vignette (`runibic.Rmd`).

3. The `runibic/vignettes/` folder is not the right place for the `NEWS` file. Please refer to the "Writing R Extensions" manual for where to put that file (https://cran.r-project.org/doc/manuals/r-release/R-exts.html).

4. Don't override `biclust::discretize()` with your own `discretize()` function. Please use a different name for the latter. In the man page explain why we need another discretization function and the differences between yours and `biclust::discretize()`. Add a `\seealso` section with a link to the `discretize()` function defined in the biclust package.

5. `runibic()` is the front-end for `runibic_d()` and `runibic_se()` so there is no need to expose and document `runibic_d()` and `runibic_se()`. At the very least the 3 functions should be documented in the same man page.

6. `set_runibic_params()` would be a better name for `runibic_params()`.

7. The \usage section in the man page for `BCUnibicD()` and `BCUnibic()` is confusing. It shows usage for 2 `"biclust"` S4 methods (one for signature `'matrix,BCUnibicD'` and one for signature `'matrix,BCUnibic'`) but these S4 methods do not exist:
    ```
    > getMethod("biclust", c("matrix", "BCUnibicD"))
    Error in getMethod("biclust", c("matrix", "BCUnibicD")) : 
      no method found for function 'biclust' and signature matrix, BCUnibicD
    > getMethod("biclust", c("matrix", "BCUnibic"))
    Error in getMethod("biclust", c("matrix", "BCUnibic")) : 
      no method found for function 'biclust' and signature matrix, BCUnibic
    ```
    Unfortunately it seems that the biclust package itself started all this confusion by doing this too. What adds to the confusion in the case of `BCUnibicD` and `BCUnibic` is that the \examples section shows how to call `BCUnibicD()` and `BCUnibic()` but these functions are not documented! So I would suggest that:
    - The \usage section shows the usage of the `BCUnibicD()` and `BCUnibic()` functions.
    - The \arguments section documents the arguments of these 2 functions.
    - The \description section mentions `BCUnibicD()` **and** `BCUnibic()`.
    - The \value section documents what `BCUnibicD()` and `BCUnibic()` return, not what the `biclust()` function returns.
    - The \examples section shows various calls to `biclust()` that illustrate the use of `BCUnibicD()` and `BCUnibic()` to actually perform the biclustering.
    - Please add a \seealso section with a link to the `biclust()` function defined in the biclust package.

8. The \description section in `?runibic` repeats the same sentence twice.

9. Overall the man pages are too minimalist. For example, after consulting the man page for `calculateLCS()` I'm not sure what this function does exactly or what it returns. Also the example that is provided doesn't really help. The man pages need to provide more details and a little bit of context. Please try to be as clear and precise as possible e.g.
    ```
    an integer vector containing the Longest Common Subsequence (LCS)
    ```
    is clearer than
    ```
    an integer with the length of Longest Common Subsequence (LCS)
    ```
    And also use consistent wording e.g. `backtrackLCS` description says it retrieves _LCS between two "**numeric** vectors"_ but then a few lines below:
    ```
    x: an **integer** vector
    y: an **integer** vector
    ```

10. The vignette is also too minimalist. The "Functions" section is poorly formatted and very hard to read (in the HTML version, which is the version that the user will see via `browseVignettes(package="runibic")`).

11. The link at the end of the vignette to the "runibic tutorial" points to an `.R` file on GitHub that contains commented R code. This is not a good idea. The runibic vignette itself should be the tutorial. It needs to be self-contained.

12. What about adding some or all of the biocViews terms suggested by `R CMD BiocCheck` (GeneExpression, Sequencing, Coverage)

13. The `NAMESPACE` file contains `exportPattern("^[[:alpha:]]+")` so all the individual `export()` directives are not needed. However, I would highly recommend that you export selectively (e.g. export `runibic` but not `runibic_d` or `runibic_se`).

14. Coding style:
    - Please make your code easier to read by using proper formatting and indentation (e.g. the example for `cluster()` is very hard to read).
    - Use the left arrow (`<-`) for assignment everywhere (instead of `=`). Place a space before and after the arrow.
    - Put a space after the comma (`,`) between the arguments of your function calls e.g.
    ```
      runibic_params(0.85, 0, 1, 100, 0)
    ```
    instead of
    ```
      runibic_params(0.85,0,1,100,0)
    ```

**Comment by athril** [comment]
Thank you for providing very valuable feedback. We'll try to implement your suggestions as soon as possible.

**Comment by athril** [comment]
We hope to have completed implementing all previous suggestions in runibic package.
The coding style and documentation of functions have been improved. Code has been reorganized. We have also merged tutorial and vignette that remained in the previous version of the package. 
Please let us know if there is anything else that could be improved in the package.

**Comment by hpages** [comment]
Hi Patryk,

Thanks for the update. There are a few leftovers, see below.

Regards,
H.

**About 4.:** Note that _links_ in the man pages of an R package are typically specified with `\link{}` or `\link[packages]{}`. So for example in the Seealso section the man page for `runiDiscretize`:
```
\seealso{
\link{set_runibic_params}

\link[biclust]{discretize}
}
```
If you do this, then the links that get displayed in the HTML browser interface (started with `help.start()`) will work. Right now they don't. Keep in mind that the whole purpose of these links is to facilitate navigating the documentation. Make sure to fix the links in the other man pages.

**About 5.:** please clean the Description section of the man page for `runibic` needs to be cleaned up:
```
Description:

     runibic: parallel row-based biclustering algorithm for analysis of
     gene expression data in R

     runibic_d

     runibic
```

**About 7.:** Maybe I was not clear enough but my suggestion was that you document `BCUnibicD()` and `BCUnibic()` in the same man page. It's all about the DRY principle (90% of the content of the 2 man pages is the same).

**About 10:** The "Functions" section was not fixed.

**About 14 (Coding style):** Please use the left arrow (`<-`) for assignment everywhere (instead of `=`), with a space before and after the arrow.

**Comment by hpages** [comment]
Hi Patryk,

Just a reminder that the BioC 3.6 release is coming very soon (Oct 31) and that we won't add new packages to it after tonight midnight EST. Passed that deadline, runibic will be added to BioC 3.7.

Regards,
H.

**Comment by athril** [comment]
We have almost resolved all the issues. The commit should be there shortly.
Thanks!
P.

**Comment by athril** [comment]
The documentation was updated. Thank you for suggestion on merging man pages of multiple functions. The manual looks cleaner and more user friendly. Could you take a look and at the newest version of the package and consider including it in BioC 3.6?

**Comment by hpages** [comment]
Why is `runibic_d` back? As I tried to explain earlier there is no benefit in exposing the `runibic` backend. Only potential confusion for the end user. You removed it from the NAMESPACE in runibic 0.99.9 but now it's back!

The "Functions" section in the vignette is still not fixed.

You're still using `=` instead of `<-` for assignment in many places.

H.

**Comment by athril** [comment]
Thanks @hpages for a fast check-up!  I thought you meant fixing Functions in man pages, not in the Vignette part. Will fix it shortly.

**Comment by hpages** [comment]
I originally reported item 10 as:

10. The vignette is also too minimalist. The "Functions" section is poorly formatted and very hard to read (in the HTML version, which is the version that the user will see via `browseVignettes(package="runibic")`).

Besides, AFAIK there is no "Functions" section in the man pages.

Please make sure to also address the other remaining issues.

Thanks,
H.

**Comment by hpages** [comment]
Sorry it seems that you actually have a Functions section in the runibic man page. This is not a predefined section. The whole man page is about  documenting 4 functions which are already listed in predefined \description and \usage sections. The recommended practice is to provide details about the individual functions in the predefined \details section.  Thanks!

**Comment by athril** [comment]
**About 4** 
multiple links were added to man pages of the package. The HTML interface `help.start()` works and allows easy navigation.
**About 5** 
Description part was fixed. In the latest commit all mentions of runibic_d were removed.
Added details section in the package.
**About 7** 
`BCUnibic`, `BCUnibicD` and `runibic` have now one manual page. Also removed all mentions of runibic_d in documentation.
**About 10** 
I refactored Functions section in Vignette.  
**About 14** 
Substituted (hopefully) all `=` occurrances with `<-`. I have also refactored some examples to match code programming guidelines.

Could you take another look at the package?

**Comment by hpages** [comment]
I don't see how putting back ticks around the function names is refactoring the Functions section in the vignette. This list of functions still does not show up as a properly formatted list in the HTML version of the vignette. But it's late and really time to move on. The other changes look good, thanks! I'm marking the package as accepted. Thank you for contributing to Bioconductor. Hopefully you change your mind for the list of functions in the vignette and fix it later. You would do your readers a great favor!

Best,
H.

**Comment by athril** [comment]
Thank you @hpages! I'll see what I can do with Functions section later on.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/athril.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"runibic\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/runibic

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
