### ISSUE TITLE
EnhancedVolcano

### ISSUE THREAD

**Issue by kevinblighe** [Bioconductor/Contributions#803]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kevinblighe/EnhancedVolcano

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by kevinblighe** [comment]
Dear Bioconductor, I had been using BiocCheck 1.14.0 and it showed no errors or warnings. I tried to update to BiocCheck 1.17.15 but it is not available on R 3.4 (which I use). R 3.5 is not yet available for Ubuntu.

I have nevertheless addressed the error and now believe that the package should pass BiocCheck.

Kind regards,
Kevin

**Comment by kevinblighe** [comment]
Dear Bioconductor, I have checked everything again and now tidied the markdown for the vignette. Everything should build correctly and pass checks without errors or warnings

**Comment by Liubuntu** [comment]
HI @kevinblighe , 

Thanks for your contribution to Bioconductor. If you have made any changes, please bump version in `DESCRIPTION` file so it will incur an automatic rebuilding. We'll see how the build report shows. Be sure to make efforts in addressing all ERROR, WARNING, or most NOTE messages before an technical review by Bioconductor core team member. Comment back here if you have any question or if ready for the technical review. 

For the R3.5, it is already available for ubuntu. It is strongly encouraged to use the most updated R version when developing R packages and it goes with the development version of Bioconductor (Currently is Bioc 3.8). 

Cheers,
Qian

**Comment by kevinblighe** [comment]
Dear Qian,  version 0.99.1 is now on my GitHub page and I am confidant that it will pass all checks without warnings or errors.

**Comment by Liubuntu** [comment]
Hi @kevinblighe , 

Please refer to this message (https://github.com/Bioconductor/Contributions/issues/803#issuecomment-404713630) under this issue and set a web hook on you repository, so that any further version bump could trigger a new build in Bioconductor. Only if the new build shows "successful without any error or warning", a technical review will be given. There will be more issues from the technical review to address, and make sure to bump the version in `DESCRIPTION` file to trigger a new build for each update. Thanks!

>IMPORTANT: Please read [the instructions](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) for setting up a push hook on your repository, or further changes to your repository will NOT trigger a new build.

Best,
Qian

**Comment by kevinblighe** [comment]
Thanks Qian! It seems to have passed all checks!

**Comment by Liubuntu** [comment]
Hi @kevinblighe , 

Yes, it builds successfully on Bioconductor. A technical review will soon be given. (within 2 weeks). 

Cheers,
Qian

**Comment by kevinblighe** [comment]
Thank you for your assistance. Kind regards, Kevin.

**Comment by kevinblighe** [comment]
Dear Qian, is there any update?

**Comment by Liubuntu** [comment]
Hi @kevinblighe , 

Sorry for the delay. I am in the middle of reviewing this package. The comments will be given this afternoon. Thanks! 

Best,
Qian

**Comment by Liubuntu** [comment]
Hi @kevinblighe , 

Thanks for your contribution to Bioconductor. It looks like a handy tool for generating publication-ready volcano plot. To you knowledge, is there any similar function in other R packages? And how to distinguish yours with others if other package returns a ggplot and user could add layers on top (e.g., add transcript names) for generating a similar one?

Following are technical reviews of your package, please seek to address all issues and comment back when you are ready for a 2nd review or have any questions. 

## DESCRIPTION 

Please add a "Depends: R (>= 3.5.0)" section. Also since your function requires the `ggplot2` package, and returns error if users doesn't have it, maybe you should add `ggplot2` into `Depends` field, so that it will be automatically installed with the installation of your own package.

## NAMESPACE
- Since you have already depends on ggplot2, Maybe you want to `import(ggplot2)` so that users could have access to other functions of `ggplot2` since they are already dealing with plots and could be flexible to do further/customized enhancement.

## man/
- looks good.

## R/
- Don't include any scripts for loading packages within your script. Do this in the `NAMESPACE` using `import(From)`. Remove the following.

```
    requireNamespace("ggplot2")
    requireNamespace("ggrepel")
```

- `ggplot2` is the only package that you import and there is no conflicting functions from other package, so please remove the `ggplot2::` before any function inside your script.

## vignette/

1. After the abstract, please add a section for "Installation" to show to users how to install the package as if it has been included in Bioconductor. Because new packages is going to be in Bioc devel (Bioc 3.8), they are required to use `BiocManager` instead of `BiocInstaller` for downing the package. You should include something like this:

```
1. Download the package from Bioconductor.

{r getPackage, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("EnhancedVolcano")

2. Load the package into R session.
{r Load, message=FALSE}
library(EnhancedVolcano)
```

You can also add a subsection for installing the developmental version
from github, e.g.,```devtools::install_github("kevinblighe/EnhancedVolcano") ```

2. add a table of contents for the vignette. ([reference](https://bookdown.org/yihui/rmarkdown/html-document.html#table-of-contents)).

3. Organize your vignette in a clearer structure with hierarchy, so that the users could has a better understanding of why do they need this package and how to use it in basic/advanced level.

for example, include :
- `Introduction/Abstract`: to include some brief introduction for what is volcano plot, what does it do, how to usually interpret the plot, and then why do we develop this enhanced volcano plot tool...
- `Installation`, as stated above.
- `Quick start`: subdirectory of "example data", "most basic volcano plot"...
- `Advanced features`: Briefly introduce the advanced features per to user's need. Use subdirectories for different advanced features.
- `SessionInfo`.

Cheers,
Qian

**Comment by Liubuntu** [comment]
Some additional comments: 

1. add documentation under "man/" for the package itself. [reference](http://r-pkgs.had.co.nz/man.html#man-packages)
2. we encourage package developers to add unit test for a robust and easy-to-debug package maintenance.

**Comment by kevinblighe** [comment]
Dear Qian,

To my knowledge, the only other function that automatically generates volcano plots in R is the volcanoplot function from limma ( https://rdrr.io/bioc/limma/man/volcanoplot.html  ); however, this function is not really designed to produce publication-ready plots. Moreover, using this function, issues with labeling of genes in the plot are common. There are 'anecdotal' references to generating other types of volcano plots scattered around the World Wide Web in blog postings, but nothing on Bioconductor.

The EnhancedVolcano project has already been starred >10 times on GitHub and has received good feedback on Biostars.

I wanted Bioconductor to have a comprehensive package / function that could generate very pretty volcano plots that were highly configurable, much like the ComplexHeatmap package is for heatmaps. In the future, I would likely expand the package, for example, for showing more than one differential expression comparison in a 3-dimensional volcano plot.

I believe there is a need for EnhancedVolcano because R is now being used by people with non-technical backgrounds who may not have the time or even expertise to learn the ggplot2 and ggrepel packages in depth. Even for regular users of R and those with experienced backgrounds in R, the package will provide a quick way to generate very nice volcano plots.

Finally, with this project, I wanted to 'revive' the use of the volcano plot such that it may once again appear in publications. I believe the volcano plot provides a quick way to visualise the results of differential expression analysis and that its usage has suffered specifically because there has been no easy way to generate very nice plots.

Note that the suggested changes for the man page introduced an error in R CMD CHECK.

The package (now version 0.99.5) is now ready for another review. Thank you!

**Comment by Liubuntu** [comment]
Hi @kevinblighe , 

Here is the 2nd review of your package. Please seek to address all issues. Bump version and comment back when you have fixed everything or have any questions. Thanks!

Best,
Qian

## NAMESPACE
- Remove the line `importFrom(ggplot2, ggplot)`. `import(ggplot2)` is supposed to import everything from `ggplot2`.

## man/
- please use a separate file to document the package itself, mostly just descriptive, with `NULL` in the body. [Refer here](http://r-pkgs.had.co.nz/man.html#man-packages).

## vignette

- in the header file, use blank space all the way to the position you want instead of using `tab` before `toc_depth: 2`, and before `toc_float: true`. This should fix the error.

- Remove the following code from vignette. The required packaged in vignette/test/examples should be specified in `Suggests` field in `DESCRIPTION`. The code for downloading packages should never appeare inside any R code or inside the vignette.

```
source("https://bioconductor.org/biocLite.R")
biocLite("airway")
```

- Use succinct sub-headers for `Advanced features`. Remove the `Example n: ` before and the ":" after each each subheader.

**Comment by kevinblighe** [comment]
Dear Qian, thank you for your assistance. I have made all suggested modifications.

**Comment by Liubuntu** [comment]
Hi @kevinblighe , 

Seems that you have lost your TOC in the vignette. Please add them back. Also add some explanatory contents under each subsection, so that the vignette could be more descriptive instead of mainly big chunks of code. 

For the documentation of package itself, Please have the script saved under "R", e.g., `R/EnhancedVolcano-package.R` using all documentation grammar, with NULL in the body, and remove the whole section in `@section EnhyancedVolcano functions: ...` because you already have it in the main function documentation. So the documentation file of `man/EnhancedVolcano-package.rd` will be generated automatically. 

Best,
Qian

**Comment by kevinblighe** [comment]
Dear Qian, I have addressed all of those issues that you mentioned. Thank you!

**Comment by Liubuntu** [comment]
Hi @kevinblighe , 

- Vignette/ 
Looks more organized and descriptive now. Thanks for the changes. 

- `R/EnhancedVolcano-package.R`
Please use `@rdname EnhancedVolcano-package` or `@name EnhancedVolcano-package` instead of `@name EnhancedVolcano`, so that the file of `man/EnhancedVolcano-package.Rd` will be generated. Currently you have 2 `R/` scripts, and they points to the same `man/EnhancedVolcano.rd` file, which is not correct. We need to make the documentation for the function and documentation for the package separately. 

Let me know for any question. Thanks,
Qian

**Comment by Liubuntu** [comment]
You still don't have the "man/EnhancedVolcano-package.rd" for the package documentation. Seems that you are not using "roxygen2" for automated documentation. Then you should manually write this rd file as "man/EnhancedVolcano-package.rd", with contents: 

```
\name{EnhancedVolcano-package}
\title{EnhancedVolcano: Publication-ready volcano plots with enhanced colouring and labeling.}

\description{Volcano plots represent a useful way to visualise the
results of differential expression analyses. Here, we present a
highly-configurable function that produces publication-ready volcano
plots. EnhancedVolcano will attempt to fit as many transcript names in
the plot window as possible, thus avoiding 'clogging' up the plot with
labels that could not otherwise have been read.}

\docType{package}
```

2. Remove the "R/EnhancedVolcano-package.R" because you are not using `roxygen2` for generating rd file from R script. 

3. Remove the line of `\docType{package}` from the `man/EnhancedVolcano.rd` since this is supposed to be the documentation for the function itself, not the package.

**Comment by kevinblighe** [comment]
Hi Qian. Thank you for your patience! I have made the required changes.

**Comment by kevinblighe** [comment]
Thank you Qian!

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kevinblighe.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"EnhancedVolcano\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/EnhancedVolcano

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
