### ISSUE TITLE
mnem

### ISSUE THREAD

**Issue by MartinFXP** [Bioconductor/Contributions#805]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cbg-ethz/mnem

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by MartinFXP** [comment]
Dear @hpages,

Thanks for the feedback. I addressed all of your concrete points accordingly and made the vignette more user friendly.

> Title of package should not be the same as its name.

Fixed.

> Man pages have titles that are the same as description. The recommended practice is to use something different for the title and the description. The title is typically shorter and the description provides more details.

Extended descriptions.

> The app dataset is a list of lists with a mysterious structure and content. The man page says "For details see the vignette" but AFAICT the vignette doesn't provide any detail about this data set. Please explain the structure and content of the data set. Also explain how it was generated.

Explanation of the data object added to vignette.

> The vignette contains too much code and almost no explanation about what the code is doing. The code seems to be generating many plots and graphs but these are not explained either.

I added echo=FALSE for code which is either for experts or just a derivation of shown code (i.e. only an index has to be changed to get the other plots).

> Check for typos e.g. "genens" instead of "genes" or "finde" instead of "find" etc... There are many!

Ran spell check.

Best,
Martin

**Comment by MartinFXP** [comment]
Dear @hpages 

I think this is now somewhat the finalised version. Unless of course I or other users find any bugs...

I hope/think the vignette now gives a good overview of what to do with this package. The warning stems from the 7+ minutes runtime of the check on the windows machine, which seems to be (not always) quite a bit slower than its mac and linux colleagues (~3 minutes). I don't think it is trivial to account for that on my end.

Thanks again for your time and all the best,
Martin

**Comment by hpages** [comment]
Hi @MartinFXP 

Thanks for the much improved vignette!

2 things still need your attention:

- Your man page titles are still the same as their description. For example opening the man page for `getIC` (e.g. with `?getIC`) displays a 4-line title that repeats the entire Description section.

- I still don't know how the `app` data set was generated. The Data Generation section of the vignette says:
    ```
    The R code for generating the data object ‘app’ is shown in the accompanying R file.
    ```
    What is the "accompanying R file"? Where is it? Note that the primary documentation for any function or data set defined in an R package is its man page so any information about how the `app` data set was generated should appear there.

Thanks,
H.

**Comment by MartinFXP** [comment]
Dear @hpages 

> * Your man page titles are still the same as their description. For example opening the man page for `getIC` (e.g. with `?getIC`) displays a 4-line title that repeats the entire Description section.

Fixed.

> * I still don't know how the `app` data set was generated. The Data Generation section of the vignette says:
>   ```
>   The R code for generating the data object ‘app’ is shown in the accompanying R file.
>   ```
>   What is the "accompanying R file"? Where is it? Note that the primary documentation for any function or data set defined in an R package is its man page so any information about how the `app` data set was generated should appear there.

I included the relevant R code into the vignette.

Thanks again for your time to help improve the quality of the package.

Best,
Martin

**Comment by hpages** [comment]
Martin,

Throwing 400+ lines of non-evaluated, hard to read, and impossible to run, code in your vignette is a very bad idea. The proper way to do these things is to put the code in a script that you include in your package. The script should be organized/structured/commented and with most of the code put inside functions, typically 1 function per major step but defining some other smaller helper functions is also a good idea and encouraged. The input of the script should be explained. Right now the 1st lines of the code is:
```
data <- read.csv("GSE92872_CROP-seq_Jurkat_TCR.digital_expression.csv", stringsAsFactors = FALSE)
```
Then hundreds lines later:
```
load(paste0(dataset, "_kegg.rda"))
load(paste0(dataset, "_llr.rda"))
```
However since we don't know anything about those files, we're back to square one, that is, we still have no idea how the `app` data set was generated. Bioconductor takes reproducibility very seriously (as it should be).

Thanks for understanding and sorry for the inconvenience,

H.

**Comment by MartinFXP** [comment]
Dear @hpages 

I cleaned and thinned out the code and put it in a function. I also did a test run to make sure it works as I totally agree, that reproducibility is very important.

```r
app <- createApp()
?createApp # can be run with different parameters for testing; even then still takes a very long time
```

I don't know why I am not registered as a subscriber to the bioc-devel mailing list. I tried to register again, but nothing happened.

The other two errors look like they are out of my control.

Best,
Martin

**Comment by hpages** [comment]
Hi @MartinFXP ,

Thanks again for all the improvements you've made to mnem.

As indicated by the build report (see output of `R CMD BiocCheckGitClone`) the package source tree contains the following compilation products: `src/mm.o`, `src/RcppExports.o`, `src/mnem.so`

This is likely to be related to the compilation error you get on Windows. Generally speaking, compilation products should never be committed to git.

The error we see on Mac looks like a problem on our side. Let's ignore it.

Best,
H.

**Comment by MartinFXP** [comment]
Dear @hpages 

regarding the last remaining error (on my side). I was subscribed to the mailing list before and for some reason and without my doing was unsubscribed. Several attempts of me to subscribe again were unsuccessful. I just get the note in the browser, that my request to subscribe was successful and I should get a notification mail once the request has been dealt with. But nothing happened. How should I go on about this?

Best,
Martin

**Comment by lshep** [comment]
Have you checked your spam or filtered emails folder?  Sometimes the email gets marked as spam.

**Comment by MartinFXP** [comment]
I have done both and got nothing.

The last Bioc-devel email I received was from September 26:
https://stat.ethz.ch/pipermail/bioc-devel/2018-September/014098.html
Nothing after that.

However, the error appeared for the first time on October 25. October 18 was still fine (https://github.com/Bioconductor/Contributions/issues/805#issuecomment-430947789). It just seems weird to me, that I didn't get any Bioc-devel mail in October, even though apparently there were some (https://stat.ethz.ch/pipermail/bioc-devel/2018-October/thread.html). 

Is it a coincidence, that the final package acceptance deadline for Bioconductor 3.8 was October 24? https://stat.ethz.ch/pipermail/bioc-devel/2018-September/014073.html

I appreciate the help.

**Comment by hpages** [comment]
Hi @MartinFXP ,

Looks like the epiNEM package was missing on celaya2 last time our Single Package Builder checked mnem, which caused mnem to fail on this machine. However, according to the [following page](https://bioconductor.org/checkResults/3.9/bioc-LATEST/celaya2-R-instpkgs.html), epiNEM is now installed on celaya2. Please bump mnem version again in order to trigger a new build by our Single Package Builder. Thanks!

H.

**Comment by MartinFXP** [comment]
Hi @hpages ,

looks like the epiNEM ERROR is gone. However, it also seems like I am again unsubscribed from the bioc-devel list. Btw, after @mtmorgan manually added me the last time, I did not receive any bioc-devel emails. Should I try to subscribe again by myself?

Thanks,
Martin

**Comment by mtmorgan** [comment]
I again resubscribed you, and you should have received an email. Please check carefully, including in your spam and junk (instititutional) email filters.

**Comment by MartinFXP** [comment]
Dear @mtmorgan ,

there actually has been a configuration error at the ETH Zurich mail service since September, which resulted in blocked r-project emails to some accounts (like mine). It has been fixed. However, since it was only fixed after my inquiry yesterday, I did not get the confirmation email after you subscribed me. Does that mean I will get unsubscribed again at one point?

Best,
Martin

**Comment by mtmorgan** [comment]
You are still subscribed; thank you for investigating on your end.

**Comment by MartinFXP** [comment]
Is there any reason this is not building? Seems to be a problem with only this package. Should I do a version bump?

**Comment by lshep** [comment]
Sorry.  I have manually kicked off a build and it should post soon.  Future version bumps should trigger a build.

**Comment by MartinFXP** [comment]
Hi,

since today is supposed to be the last day for new packages, is there anything still wrong with this package? No errors or warnings and as far as I can see, I fixed all issues addressed in the review(s).

Best,
Martin

**Comment by hpages** [comment]
Hi Martin,

Sorry for the late answer. We've delayed the BioC 3.9 release by a few days. mnem will be part of it.

Cheers,
H.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MartinFXP.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("mnem")`. The package 'landing page' will be created at

https://bioconductor.org/packages/mnem

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
