### ISSUE TITLE
PepsNMRData

### ISSUE THREAD

**Issue by ManonMartin** [Bioconductor/Contributions#877]
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ManonMartin/PepsNMRData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by ManonMartin** [comment]
AdditionalPackage: https://github.com/username/repositoryname

**Comment by hpages** [comment]
Hi Manon,

Thanks for submitting the PepsNMR package and its accompanying data package PepsNMRData. The package feels well polished, with good documentation and a very nice vignette. It will be a welcome addition to Bioconductor which doesn't have much to offer right now in the department of 1H NMR data. The only package I know that was dealing with this type of data was [mQTL.NMR](https://bioconductor.org/packages/mQTL.NMR) but it got deprecated about 2 weeks ago and won't make it in the BioC 3.8 release.

Here are a few minor issues that need your attention:

1. Do not use `devtools::install_github` in your vignette to install the package. Once a package is part of Bioconductor, it should be installed with `BiocManager::install()` i.e. with:
    ```
    if (!requireNamespace("BiocManager", quietly = TRUE))
        install.packages("BiocManager")
    BiocManager::install("PepsNMR")
    ```
    Please show this instead.
    See for example https://bioconductor.org/packages/devel/GenomicRanges for how to install the GenomicRanges package. It's ok to add a note showing how to install the development version of the package though but please make it clear that, unless the user knows what s/he's doing, this should be avoided as it can lead to package version mismatch hell.

2. You need to add a `.R` or `.Rin` file in the `tests/` directory or `R CMD check` will not run the unit tests.

3. Use `TRUE`/`FALSE` instead of `T`/`F`.

4. PepsNMRData is in the Imports field of the DESCRIPTION file but doesn't actually get imported (it does not appear in the NAMESPACE file). This suggests that it should be in the Depends field instead.

5. For graphics and stats, it's the other way around. Since they appear in the NAMESPACE file, they should also be listed in the Imports field of the DESCRIPTION file.

Thanks,
H.

**Comment by ManonMartin** [comment]
Hi Hervé,

All these issues should be fixed by now. 
Few remarks: 
- Issue 1 : I also modified Githubpkg() into Biocpkg() to refer to the package repos on Bioconductor (yet to be created).
- Issue 2: I removed the testthat tests for now as they were not currently used and should be completed and improved before their application.

Best,
Manon

**Comment by hpages** [comment]
Hi Manon,

Thanks for those changes.

Note that you still have a few occurrences of T and F in your code:
```
hpages@spectre:~/PepsNMR/R$ grep -w T *
PCA.R:      if (T | z[i, ndesign.couleur] == valeurfacteur.couleur[id.facteur.couleur])   {
Warping.R:            stop("WCC is only implemented in ptw, set ptw.wp=T to use WCC.")
hpages@spectre:~/PepsNMR/R$ grep -w F *
Bucketing.R:        trapz_right <- base::rowSums(sweep(Spectrum_data[, from:(to - 1), drop = F], 
Bucketing.R:        trapz_left <- base::rowSums(sweep(Spectrum_data[, (from + 1):to, drop = F], 
DrawPCA.R:          show.legend = F, size = 2)
```
Also I realize now that PepsNMRData is only used in the examples and vignette so should actually go in Suggests and not Depends. This will avoid getting the following `R CMD check` note:
```
* checking dependencies in R code ... NOTE
Package in Depends field not imported from: ‘PepsNMRData’
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
```
Sorry for misleading you earlier.

Other than that everything looks great now.

Cheers,
H.

**Comment by hpages** [comment]
Hi Manon, any progress on this? Monday would be the last day for adding the package to BioC 3.8.

Thanks,
H.

**Comment by ManonMartin** [comment]
Hi Hervé,

I made the modifications and pushed to github but now Travis identified an error, which I suspect is due to the PepsNMRData dependency. I am away with no access to my computer to modify the R code until 11th of November so I think it will have to wait until the next release unfortunately.

Best,
Manon

Le 26 oct. 2018 à 19:08, hpages <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi Manon, any progress on this? Monday would be the last day for adding the package to BioC 3.8.

Thanks,
H.

**Comment by hpages** [comment]
Hi Manon,

The last 2 issues I reported (`T` and `F` in your code and moving PepsNMRData from Depends to Suggests) are really minor ones and should not prevent the package from being added to BioC 3.8. So I'm accepting the package. I count on you to address these 2 minor issues when you get a chance.

Cheers,
H.

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ManonMartin.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PepsNMRData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PepsNMRData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment]
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ManonMartin.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PepsNMR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PepsNMR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/
